spring:
  application:
    name: lol-arena
  datasource:
    url: jdbc:postgresql://localhost:5432/lol_arena
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

