-- Refresh descriptions, tiers, and notes from backend/augments-updated.txt
-- Overwrites the data set by V6__populate_augment_descriptions.sql
-- Updates by name (not id) so it is robust to reordering or re-tiering.

UPDATE augments SET description = 'Casting an ability grants {{sti|{{as|ability haste}}}}. This effect stacks infinitely and lasts until the end of the current round phase.', tier = 'Prismatic', notes = NULL WHERE name = 'Accelerating Sorcery';
UPDATE augments SET description = 'Convert ''''''all'''''' of your {{sti|{{as|''''''bonus'''''' attack damage}}}} into {{sti|{{as|ability power}}}}. Additionally, increase your {{as|ability power by a percentage}}.', tier = 'Silver', notes = '* {{ci|Ryze}} cannot receive this augment.' WHERE name = 'ADAPt';
UPDATE augments SET description = 'The effectiveness of your {{tip|heals}} and {{tip|shields}} is increased on allied champions.', tier = 'Gold', notes = NULL WHERE name = 'All For You';
UPDATE augments SET description = 'Grants {{sti|ability haste|{{as|item haste|ability haste}}}}.', tier = 'Gold', notes = '{| class="article-table article-table-selected" style="width: 750px;
! rowspan="1" colspan="11" style="width:150px; text-align:center;" | Item Cooldowns
|-{{#vardefine:AIHaste|100}}
|-{{#vardefine:AIHaste2|300}}
! style="text-align:center;" |Items
! style="text-align:center;" |Base Cooldown
! style="text-align:center;" |Reduced Cooldown with [[File:Apex Inventor ar augment.png|35px|link=|An icon for the Arena augment Apex Inventor]] Apex Inventor
! style="text-align:center;" |Reduced Cooldown with level 2 [[File:Apex Inventor ar augment.png|35px|link=|An icon for the Arena augment Apex Inventor]] Apex Inventor
|-
! style="text-align:center;" | {{ii|Diadem of Songs|icononly=yes}}
| style="text-align:center;" |{{fd|1}} 
| style="text-align:center;" |{{fd|{{#expr:(1-1*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}}}
| style="text-align:center;" |{{fd|{{#expr:(1-1*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}}}
|-
! style="text-align:center;" | {{ii|Divine Sunderer|icononly=yes}}{{ii|Dusk and Dawn|icononly=yes}}{{ii|Iceborn Gauntlet|icononly=yes}}{{ii|Lich Bane|icononly=yes}}{{ii|Trinity Force|icononly=yes}}
| style="text-align:center;" |{{fd|1.5}} 
| style="text-align:center;" |{{fd|{{#expr:(1.5-1.5*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}}}
| style="text-align:center;" |{{fd|{{#expr:(1.5-1.5*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}}}
|-
! style="text-align:center;" | {{ii|Malignance|icononly=yes}}{{ii|Pyromancer''s Cloak|icononly=yes}}{{tt|*|Cleansing Flame}}
| style="text-align:center;" |3
| style="text-align:center;" |{{fd|{{#expr:(3-3*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}}}
| style="text-align:center;" |{{fd|{{#expr:(3-3*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}}}
|-
! style="text-align:center;" | {{ii|Unending Despair|icononly=yes}}
| style="text-align:center;" |4
| style="text-align:center;" |{{#expr:(4-4*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}
| style="text-align:center;" |{{#expr:(4-4*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}
|-
! style="text-align:center;" | {{ii|Pyromancer''s Cloak|icononly=yes}}{{tt|*|Spark}}
| style="text-align:center;" |5
| style="text-align:center;" |{{#expr:(6-6*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}
| style="text-align:center;" |{{#expr:(6-6*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}
|-
! style="text-align:center;" | {{ii|Cruelty|icononly=yes}}{{ii|Eclipse|icononly=yes}}{{ii|Luden''s Echo|icononly=yes}}
| style="text-align:center;" |6
| style="text-align:center;" |{{#expr:(6-6*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}
| style="text-align:center;" |{{#expr:(6-6*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}
|-
! style="text-align:center;" | {{ii|Sundered Sky|icononly=yes}}
| style="text-align:center;" |8
| style="text-align:center;" |{{#expr:(6-6*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}
| style="text-align:center;" |{{#expr:(6-6*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}
|-
! style="text-align:center;" | {{ii|Imperial Mandate|icononly=yes}}
| style="text-align:center;" |9 
| style="text-align:center;" |{{fd|{{#expr:(9-9*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}}}
| style="text-align:center;" |{{fd|{{#expr:(9-9*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}}}
|-
! style="text-align:center;" | {{ii|Hellfire Hatchet|icononly=yes}}{{ii|Hexbolt Companion|icononly=yes}}{{ii|Night Harvester|icononly=yes}}{{ii|Profane Hydra|icononly=yes}}{{ii|Ravenous Hydra|icononly=yes}}{{ii|Titanic Hydra|icononly=yes}}{{ii|Wordless Promise|icononly=yes}}
| style="text-align:center;" |10 
| style="text-align:center;" |{{#expr:(10-10*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}
| style="text-align:center;" |{{#expr:(10-10*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}
|-
! style="text-align:center;" | {{ii|Reality Fracture|icononly=yes}}
| style="text-align:center;" |12
| style="text-align:center;" |{{#expr:(12-12*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}
| style="text-align:center;" |{{#expr:(12-12*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}
|-
! style="text-align:center;" | {{ii|Blade of the Ruined King|icononly=yes}}{{ii|Ghostcrawlers|icononly=yes}}{{ii|Goredrinker|icononly=yes}}{{ii|Spectral Cutlass|icononly=yes}}{{ii|Stridebreaker|icononly=yes}}
| style="text-align:center;" |15 
| style="text-align:center;" |{{fd|{{#expr:(15-15*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}}}
| style="text-align:center;" |{{fd|{{#expr:(15-15*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}}}
|-
! style="text-align:center;" | {{ii|Lightning Rod|icononly=yes}}
| style="text-align:center;" |16
| style="text-align:center;" |{{fd|{{#expr:(15-15*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}}}
| style="text-align:center;" |{{fd|{{#expr:(15-15*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}}}
|-
! style="text-align:center;" | {{ii|Edge of Night|icononly=yes}}{{ii|Empyrean Promise|icononly=yes}}{{ii|Fiendhunter Bolts|icononly=yes}}{{ii|Turbo Chemtank|icononly=yes}}{{ii|Wooglet''s Witchcap|icononly=yes}}{{ii|Youmuu''s Ghostblade|icononly=yes}}
| style="text-align:center;" |20 
| style="text-align:center;" |{{fd|{{#expr:(20-20*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}}}
| style="text-align:center;" |{{fd|{{#expr:(20-20*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}}}
|-
! style="text-align:center;" | {{ii|Hextech Rocketbelt|icononly=yes}}{{ii|Prowler''s Claw|icononly=yes}}{{ii|Puppeteer|icononly=yes}}
| style="text-align:center;" |25
| style="text-align:center;" |{{fd|{{#expr:(20-20*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}}}
| style="text-align:center;" |{{fd|{{#expr:(20-20*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}}}
|-
! style="text-align:center;" | {{ii|Banshee''s Veil|icononly=yes}}{{ii|Black Hole Gauntlet|icononly=yes}}{{ii|Crown of the Shattered Queen|icononly=yes}}{{ii|Everfrost|icononly=yes}}{{ii|Experimental Hexplate|icononly=yes}}{{ii|Galeforce|icononly=yes}}{{ii|Gargoyle Stoneplate|icononly=yes}}{{ii|Heartsteel|icononly=yes}}{{ii|Hextech Gunblade|icononly=yes}}{{ii|Horizon Focus|icononly=yes}}{{ii|Maw of Malmortius|icononly=yes}}{{ii|Mikael''s Blessing|icononly=true}}{{ii|Radiant Virtue|icononly=yes}}{{ii|Shurelya''s Battlesong|icononly=yes}}{{ii|Sterak''s Gage|icononly=yes}}{{ii|Stormsurge|icononly=yes}}{{ii|Yun Tal Wildarrows|icononly=yes}}{{ii|Zeke''s Convergence|icononly=yes}}
| style="text-align:center;" |30 
| style="text-align:center;" |{{#expr:(30-30*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}
| style="text-align:center;" |{{#expr:(30-30*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}
|-
! style="text-align:center;" | {{ii|Locket of the Iron Solari|icononly=yes}}{{ii|Mercurial Scimitar|icononly=yes}}{{ii|Redemption|icononly=yes}}{{ii|Seraph''s Embrace|icononly=yes}}
| style="text-align:center;" |45 
| style="text-align:center;" |{{fd|{{#expr:(45-45*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}}}
| style="text-align:center;" |{{fd|{{#expr:(45-45*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}}}
|-
! style="text-align:center;" | {{ii|Actualizer|icononly=yes}}{{ii|Cryptbloom|icononly=yes}}{{ii|Knight''s Vow|icononly=yes}}
| style="text-align:center;" |60 
| style="text-align:center;" |{{#expr:(60-60*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}
| style="text-align:center;" |{{#expr:(60-60*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}
|-
! style="text-align:center;" | {{ii|Anathema''s Chains|icononly=yes}}{{ii|Immortal Shieldbow|icononly=yes}}{{ii|Randuin''s Omen|icononly=yes}}{{ii|Protoplasm Harness|icononly=yes}}
| style="text-align:center;" |90
| style="text-align:center;" |{{#expr:(90-90*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}
| style="text-align:center;" |{{#expr:(90-90*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}
|-
! style="text-align:center;" | {{ii|Zhonya''s Hourglass|icononly=true}}
| style="text-align:center;" |120
| style="text-align:center;" |{{#expr:(120-120*(1-1/(1+({{#var:AIHaste}})/100))) round 2}}
| style="text-align:center;" |{{#expr:(120-120*(1-1/(1+({{#var:AIHaste2}})/100))) round 2}}' WHERE name = 'Apex Inventor';
UPDATE augments SET description = 'Your [[champion ability|champion abilities]] deal increased damage and you gain {{sti|{{as|ability haste}}}} and increased {{tip|heal|healing}} and {{tip|shield|shielding}} from all sources, but your ultimate ability is permanently {{tip|lockout|sealed}}.', tier = 'Prismatic', notes = NULL WHERE name = 'Back to Basics';
UPDATE augments SET description = 'Replaces {{si|Flee}} with ''''{{si|Banner of Command}}''''.<br><br>[[File:Banner of Command augment spell.png|20px|link=]] {{sbc|Banner of Command:}} {{#invoke:SpellData|geteffect|Banner of Command}}', tier = 'Gold', notes = NULL WHERE name = 'Banner of Command';
UPDATE augments SET description = 'At the start of the combat phase in each round, gain a {{tip|shield}} that absorbs damage equal to a multiple of your {{sti|{{as|AP}}}} and lasts until destroyed.', tier = 'Gold', notes = NULL WHERE name = 'Big Brain';
UPDATE augments SET description = 'Replaces {{si|Flee}} with ''''{{si|Blade Waltz}}''''.<br><br>[[File:Blade Waltz augment spell.png|20px|link=]] {{sbc|Blade Waltz:}} {{#invoke:SpellData|geteffect|Blade Waltz}}', tier = 'Prismatic', notes = NULL WHERE name = 'Blade Waltz';
UPDATE augments SET description = 'Gain {{cai|Hemorrhage|Darius}}.<br><br>{{sbc|Passive:}} Damaging basic attacks and abilities apply a stack of ''''Hemorrhage'''' to enemies for 5 seconds, refreshing on subsequent applications and stacking up to 5 times.<br><br>{{sbc|Hemorrhage:}} For each stack, the target is dealt {{ft|{{as|{{pp|15 to 45}}|physical damage}} {{as|(+ 40% AD)}} {{as|''''''total'''''' physical damage}}|{{as|{{pp|15/4 to 45/4}}|physical damage}} {{as|(+ {{ap|40/4}}% AD)}} {{as|physical damage}} every {{fd|1.25}} seconds}} over the duration, up to a maximum of{{ft|{{as|{{pp|15*5 to 45*5}}|physical damage}} {{as|(+ {{ap|40*5}}% AD)}} {{as|''''''total'''''' physical damage}} over the duration.|{{as|{{pp|(15/4)*5 to (45/4)*5}}|physical damage}} {{as|(+ {{ap|(40/4)*5}}% AD)}} {{as|physical damage}} with each tick.}}<br><br>{{sbc|Noxian Might:}} When you apply 5 stacks of ''''Hemorrhage'''' to an enemy champion, become empowered with ''''Noxian Might'''' for 5 seconds, granting you {{pp|30 to 75 for 10;90 to 120 for 3;150 to 270 for 5|formula=30 + 5 per level until level 10, then + 15 per level until level 13, then + 30 per level|color=AD}} {{sti|{{as|''''''bonus'''''' attack damage}}}}.<br><br>''''This augment is only available for {{ci|Draven}}.''''', tier = 'Gold', notes = NULL WHERE name = 'Blood Brother';
UPDATE augments SET description = 'Increases {{sti|{{as|''''''total'''''' attack damage}}}} by a percentage.', tier = 'Silver', notes = NULL WHERE name = 'Blunt Force';
UPDATE augments SET description = 'Your champion''s first basic ability ''''(Q)'''' gains {{sti|{{as|ability haste}}}}.', tier = 'Gold', notes = NULL WHERE name = 'Bread And Butter';
UPDATE augments SET description = 'Your champion''s third basic ability ''''(E)'''' gains {{sti|{{as|ability haste}}}}.', tier = 'Gold', notes = NULL WHERE name = 'Bread And Cheese';
UPDATE augments SET description = 'Your champion''s second basic ability ''''(W)'''' gains {{sti|{{as|ability haste}}}}.', tier = 'Gold', notes = NULL WHERE name = 'Bread And Jam';
UPDATE augments SET description = 'Grants {{bi|Crest of Cinders}} and {{bi|Crest of Insight}} permanently.<br><br>This counts as a {{as|Burn}} source.', tier = 'Silver', notes = NULL WHERE name = 'Buff Buddies';
UPDATE augments SET description = 'Casting your ultimate grants you {{tip|invulnerability}} for 2 seconds ({{sti|8 seconds cooldown}}).', tier = 'Prismatic', notes = NULL WHERE name = 'Can''t Touch This';
UPDATE augments SET description = 'At the start of the combat phase in each round, launch yourself from a [[catapult]].<br><br>The catapult lasts for up to 20 seconds before expiring.', tier = 'Silver', notes = NULL WHERE name = 'Cannon Fodder';
UPDATE augments SET description = 'Replaces {{si|Flee}} with ''''{{si|Castle}}''''.<br><br>[[File:Castle augment spell.png|20px|link=]] {{sbc|Castle:}} {{#invoke:SpellData|geteffect|Castle}}', tier = 'Silver', notes = NULL WHERE name = 'Castle';
UPDATE augments SET description = 'Gain {{sti|{{as|''''''bonus'''''' health}}}}, but reduce your damage output.', tier = 'Gold', notes = NULL WHERE name = 'Celestial Body';
UPDATE augments SET description = 'Gain {{cai|Center of the Universe|Aurelion Sol}}.<br><br>{{sbc|Center of the Universe:}} You are now permanently orbited by 6 ''''Stars'''' that exist {{tt|at your attack range|At the beginning of the current phase}}, and rotate clockwise one after another at the same constant speed.<br><br>Each ''''Star'''' deals {{as|{{pp|5 to 160}}|magic damage}} {{as|(+ 25% ''''''bonus'''''' AD)}} {{as|(+ 12% AP)}} {{as|magic damage}} to enemies that come into contact with it and has a width of {{tip|er|icononly=true}} 50 units.', tier = 'Prismatic', notes = NULL WHERE name = 'Center of the Universe';
UPDATE augments SET description = 'Dealing damage to an enemy champion also damages the nearest other champion within 800 units of them for {{sti|{{as|true damage}}}} equal to a portion of damage instance {{tt|post-mitigation|Damage calculated after modifiers}}.', tier = 'Prismatic', notes = NULL WHERE name = 'Chain Lightning';
UPDATE augments SET description = 'Become {{tip|attach|attached}} to your ally for the rest of the game, granting them {{sti|{{as|100% of your ''''''bonus'''''' movement speed}}}} as well as gaining {{sti|{{as|ability haste}}}} and {{sti|{{as|''''''bonus'''''' attack speed}}}}.<br><br>{{tip|Dash|Dashing}} or {{tip|blink|blinking}} detaches you for {{fd|1.5}} seconds before attaching you back to your ally. While your ally is downed, the link is temporarily broken.', tier = 'Prismatic', notes = '* When {{cai|The Show Stopper|Sett}} is used on you, you will not reattach to your ally until you {{tip|dash}} or {{tip|blink}} again.
        * When {{cai|Realm of Death|Mordekaiser}} is used on you, your hitbox stays attached to your ally''s location while you appear to stand at the position where you entered the ''''Death Realm''''.{{bug}}
        ** When casting an ability, your champion will ''''''visually'''''' teleport to your real location, before ''''''visually'''''' teleporting back once the cast is over.
        * When {{cai|Realm of Death|Mordekaiser}} is used on your ally, you will follow them into the ''''Death Realm''''.
        ** You will, however, only follow them back out of the ''''Death Realm'''' if you are attached or once you reattach to them.{{bug}}
        *** In the case that you find a way to never reattach, you can stay in the ''''Death Realm'''' until the round is over.' WHERE name = 'Chauffeur';
UPDATE augments SET description = '{{tip|Heal|Healing}} and {{stil|health regeneration}} you do causes you to deal a ratio of that value in {{as|magic damage}} to the nearest enemy champion within 1000 units.', tier = 'Prismatic', notes = NULL WHERE name = 'Circle of Death';
UPDATE augments SET description = 'Form a {{tip|tether}} between you and your ally that continuously {{as|Burns}} enemies it touches, dealing {{as|magic damage}} every {{fd|0.25}} seconds. The tether has a width of {{tip|er|icononly=true}} 100 units. ''''Attributes the damage to the player who has equipped Clothesline.''''', tier = 'Silver', notes = NULL WHERE name = 'Clothesline';
UPDATE augments SET description = 'Gain the {{ri|Electrocute}} and {{ri|Phase Rush}} keystone runes.<br><br>''''See [[Arena#Runes]] for Arena-specific overrides on these runes.''''', tier = 'Gold', notes = NULL WHERE name = 'Combo Master';
UPDATE augments SET description = 'At the start of the combat phase in each round, mark a champion on the enemy team. The mark causes them to take increased damage from your team and dispense an ''''''additional'''''' kill bounty of {{g|150}} when slain. This bounty is granted to both you and your ally when the marked target is slain.<br><br>Each enemy champion can only have one mark per round.', tier = 'Silver', notes = NULL WHERE name = 'Contract Killer';
UPDATE augments SET description = '{{tip|immobilize|Immobilizing}} or {{tip|ground|grounding}} an enemy champion grants a shield based on {{as|your ''''''maximum'''''' health}} for 3 seconds ({{sti|5 seconds cooldown}} per {{tip|cast instance}}). Shields can stack between multiple triggers of this effect, though not refreshing the duration of previous shields.', tier = 'Prismatic', notes = NULL WHERE name = 'Courage of the Colossus';
UPDATE augments SET description = 'Your {{tip|heals}} and {{tip|shields}} now have a chance equal to your {{sti|{{as|critical strike chance}}}} to increase. The effectiveness benefits from your {{sti|critical strike damage|{{as|crit damage}}}}. Additionally, gain {{sti|{{as|25% critical strike chance}}}}.', tier = 'Gold', notes = NULL WHERE name = 'Critical Healing';
UPDATE augments SET description = 'Abilities with {{tip|dash|dashes}} or {{tip|blink|blinks}} gain {{sti|{{as|ability haste}}}}.<br><br>On {{ci|Kalista}}, {{ais|Martial Poise|Kalista}} dash gains {{sti|{{as|''''''bonus'''''' movement speed}}}} toward its speed scaling instead.', tier = 'Prismatic', notes = NULL WHERE name = 'Dashing';
UPDATE augments SET description = 'Upon dropping below {{sti|{{as|60% ''''''maximum'''''' health}}}} for the first time, you are {{tip|heal|healed}} for {{sti|{{as|a certain amount of ''''''maximum'''''' health}}}} over 3 seconds.', tier = 'Gold', notes = NULL WHERE name = 'Dawnbringer''s Resolve';
UPDATE augments SET description = 'Replaces {{si|Flee}} with ''''{{si|Defensive Maneuvers}}''''.<br><br>[[File:Defensive Maneuvers augment spell.png|20px|link=]] {{sbc|Defensive Maneuvers:}} {{#invoke:SpellData|geteffect|Defensive Maneuvers}}<br><br>{{#invoke:SpellData|geteffect2|Defensive Maneuvers}}<br><br>{{#invoke:SpellData|geteffect3|Defensive Maneuvers}}', tier = 'Gold', notes = NULL WHERE name = 'Defensive Maneuvers';
UPDATE augments SET description = 'Grants {{sti|{{as|''''''bonus'''''' attack speed}}}}.', tier = 'Silver', notes = NULL WHERE name = 'Deft';
UPDATE augments SET description = 'Scoring a champion {{tip|takedown}} grants permanent {{as|adaptive force}}. This effect can be triggered only once per champion per round.<br><br>If this is your second augment, also gain {{adaptive|30}}.', tier = 'Silver', notes = NULL WHERE name = 'Dematerialize';
UPDATE augments SET description = 'Gain the {{ri|Fleet Footwork}} and {{ri|Grasp of the Undying}} keystone runes.<br><br>''''See [[Arena#Runes]] for Arena-specific overrides on these runes.''''', tier = 'Gold', notes = NULL WHERE name = 'Demon''s Dance';
UPDATE augments SET description = 'Replaces {{si|Flee}} with ''''{{si|Die Another Day}}''''.<br><br>[[File:Lamb''s Respite.png|20px|link=]] {{sbc|Die Another Day:}} {{#invoke:SpellData|geteffect|Die Another Day}}', tier = 'Gold', notes = NULL WHERE name = 'Die Another Day';
UPDATE augments SET description = 'Your team''s first death each round creates an explosion at the location of the champion that died, dealing {{as|true damage}} equal to {{sti|{{as|a percentage of the target''s ''''''maximum'''''' health}}}} to enemies within 500 units. ''''This effect cannot award victory to the user if they are the last one standing on their team.''''', tier = 'Silver', notes = NULL WHERE name = 'Dive Bomber';
UPDATE augments SET description = 'Deal increased damage based on {{sti|{{as|movement speed}}}} you have more than the target.', tier = 'Silver', notes = NULL WHERE name = 'Don''t Blink';
UPDATE augments SET description = 'Gain and activate {{cai|Poison Trail|Singed}}.<br><br>{{sbc|Poison Trail:}} Gain {{tip|ghosting}} and continually create a toxic cloud behind you that lingers for {{fd|3.25}} seconds. The cloud inflicts {{tip|poison}} to enemies within every {{fd|0.5}} seconds, which deals {{as|{{pp|15/4 to 125/4}}|magic damage}} {{as|(+ {{ap|20/4}}% ''''''bonus'''''' AD)}} {{as|(+ {{ap|10/4}}% AP)}} {{as|magic damage}} every {{fd|0.25}} seconds over 2 seconds.', tier = 'Silver', notes = NULL WHERE name = 'Don''t Chase';
UPDATE augments SET description = 'Become {{tip|melee}}, modifying your [[attack range]] to 200 units. Additionally, gain {{sti|{{as|''''''bonus'''''' attack damage}}}}, {{sti|{{as|''''''bonus'''''' attack speed}}}}, {{sti|{{as|''''''bonus'''''' health}}}}, {{sti|{{as|15% ''''''bonus'''''' movement speed}}}} and {{sti|{{as|25% life steal}}}}. These bonuses are increased by {{pp|key=%|type=champion''s default attack range|0 to 30 for 11|500 to 650|formula=3% for every 15 attack range starting from 500 attack range and with the maximum at 650 range}}.<br><br>''''This augment is only available for {{tip|ranged}} champions.''''', tier = 'Prismatic', notes = NULL WHERE name = 'Draw Your Sword';
UPDATE augments SET description = 'Your basic attacks launch a bolt at the target that fires after a {{tt|{{fd|0.225}}-second delay|Estimated}} {{tip|on-attack}}, deals 40% damage of the triggering attack''s {{tt|pre-mitigation|Damage calculated before modifiers}} damage, and applies {{tip|on-hit}} effects at 40% effectiveness. Additionally, increase your {{sti|{{as|''''''total'''''' attack speed}}}}.', tier = 'Prismatic', notes = NULL WHERE name = 'Dual Wield';
UPDATE augments SET description = '{{tip|Dash|Dashing}} or {{tip|blink|blinking}} causes you to leave behind a trail {{tip|cr|icononly=true}} from the location you moved to your destination that detonates after {{fd|0.75}} seconds in a 300 radius, dealing {{as|physical damage}} per explosion to enemies hit. Enemies can only be affected once every {{fd|0.5}} seconds from all cast instances.', tier = 'Prismatic', notes = NULL WHERE name = 'Earthwake';
UPDATE augments SET description = 'Each instance of damage dealt to an enemy reduces their {{sti|{{as|armor}}}} and {{sti|{{as|magic resistance}}}} for 4 seconds, stacking up to 20 times.', tier = 'Silver', notes = NULL WHERE name = 'Erosion';
UPDATE augments SET description = 'Convert ''''''all'''''' of your {{sti|{{as|ability power}}}} into {{sti|{{as|''''''bonus'''''' attack damage}}}}. Additionally, increase your {{sti|{{as|''''''total'''''' attack damage}}}}.', tier = 'Silver', notes = NULL WHERE name = 'EscAPADe';
UPDATE augments SET description = 'Your abilities apply {{tip|on-hit}} effects at 100% effectiveness a number of times ({{sti|1 second cooldown}} per target).', tier = 'Gold', notes = NULL WHERE name = 'Ethereal Weapon';
UPDATE augments SET description = 'Gain {{sti|{{as|ability haste}}}} based on your {{sti|{{as|ability power}}}}.', tier = 'Prismatic', notes = NULL WHERE name = 'Eureka';
UPDATE augments SET description = 'Deal increased damage to enemies below {{as|a certain health threshold}}. Scoring a champion {{tip|takedown}} resets the cooldown of all your basic abilities.', tier = 'Silver', notes = NULL WHERE name = 'Executioner';
UPDATE augments SET description = '{{as|Automatically}} cast {{cai|Rocket Grab|Blitzcrank}} at a nearby enemy champion, {{tip|airborne|pulling}} the first target hit towards you and {{tip|stun|stunning}} them for 1 second ({{sti|12 seconds cooldown}}).', tier = 'Gold', notes = NULL WHERE name = 'Extendo-Arm';
UPDATE augments SET description = 'At the start of the combat phase in each round, gain {{cai|Black Shield|Morgana}}, granting you a {{tip|shield}} that absorbs {{as|magic damage}} and grants {{tip|cc-immune|crowd control immunity}} while it holds.<br><br>''''The shield''s duration is refreshed once the initial delay for the combat phase is over.''''', tier = 'Silver', notes = NULL WHERE name = 'Fallen Aegis';
UPDATE augments SET description = 'Your next basic attack in each cardinal direction within {{sti|attack range|750 range}} additionally {{tip|on-attack}} fires 5 bolts at the target that each deals {{as|{{pp|10 to 52.5}}|physical damage}} {{as|(+ 15% ''''''bonus'''''' AD)}} {{as|physical damage}}. Each direction has {{sti|unique cooldown}}. Bolts'' damage is increased by {{pp|type=distance travelled|0 to 50 for 11|0 to 750|key=%}}. Each bolt can {{tip|critically strike}} and applies {{tip|on-hit}} effects at 20% effectiveness.', tier = 'Prismatic', notes = NULL WHERE name = 'Fan the Hammer';
UPDATE augments SET description = 'Replaces {{si|Flee}} with ''''{{si|Feel the Burn}}''''.<br><br>[[File:Feel the Burn augment spell.png|20px|link=]] {{sbc|Feel the Burn:}} {{#invoke:SpellData|geteffect|Feel the Burn}}<br><br>This counts as a {{as|Burn}} source.', tier = 'Prismatic', notes = NULL WHERE name = 'Feel the Burn';
UPDATE augments SET description = 'Damaging enemies with your ultimate ability {{tip|polymorph|polymorphs}} them into harmless critters for 2 seconds, during which their {{sti|{{as|''''''base'''''' movement speed}}}} is reduced by {{as|60|ms}}, and {{tip|disarm|disarms}} them for the same duration ({{sti|15 seconds cooldown}} per target).', tier = 'Prismatic', notes = NULL WHERE name = 'Fey Magic';
UPDATE augments SET description = 'Upon selecting this augment, all of your current items are sold to the shop at a higher {{g|gold}} value ''''({{sbc|Starter Items & Boots:}} {{g|500}}, {{sbc|Legendary Item:}} {{g|2500}}, {{sbc|Prismatic Item:}} {{g|4000}}).''''<br><br>Quest items ({{ii|Needlessly Large Rod}}, {{ii|The Golden Spatula}}, {{ii|Wooglet''s Witchcap}}, as well as {{ii|Heartsteel}} if you have the [[File:Quest Steel Your Heart ar augment.png|20px|link=]] ''''Quest: Steel Your Heart'''' augment) and consumables will not be sold from this effect.<br><br>When this augment is removed or replaced, gain {{g|gold}} equal to 30% of {{g|gold}} gained from this augment.', tier = 'Silver', notes = NULL WHERE name = 'Fire Sale';
UPDATE augments SET description = 'Basic attacks {{tip|on-hit}} apply a {{as|Burn}} for 5 seconds that deals {{as|''''''bonus'''''' magic damage}} based on {{as|the target''s ''''''maximum'''''' health}}. This {{as|Burn}} stacks infinitely and refreshes with each application.<br><br>This counts as a {{as|Burn}} source.', tier = 'Gold', notes = NULL WHERE name = 'Firebrand';
UPDATE augments SET description = 'Grants {{stil|{{as|heal and shield power}}}}.', tier = 'Silver', notes = NULL WHERE name = 'First-Aid Kit';
UPDATE augments SET description = 'Using {{si|Flash}} creates an explosion around the blink location that deals {{as|{{pp|70 to 240}}|magic damage}} {{as|(+ 70% AD)}} {{as|(+ 60% AP)}} {{as|magic damage}} to nearby enemies and {{tip|slow|slows}} them by 35% for {{fd|1.25}} seconds. Additionally, the cooldown of your {{si|Flash}} resets every round.<br><br>''''Removed since [[V26.09]].''''', tier = 'Silver', notes = NULL WHERE name = 'Flashbang';
UPDATE augments SET description = 'Your {{si|Flash}} now has multiple charges with a {{sti|2-second cooldown}} between casts, gaining maximum charges at the start of each phase in a round. Additionally, the cooldown of your {{si|Flash}} resets every round.', tier = 'Gold', notes = NULL WHERE name = 'Flashy';
UPDATE augments SET description = 'Gain the {{ri|Dark Harvest}} and {{ri|First Strike}} keystone runes. Additionally, for each augment equipped before selecting this one, gain 8 {{as|Souls}} of {{ri|Dark Harvest}} for free.<br><br>''''See [[Arena#Runes]] for Arena-specific overrides on these keystones.''''', tier = 'Gold', notes = NULL WHERE name = 'From Beginning to End';
UPDATE augments SET description = '{{as|Automatically}} cast {{cai|Ring of Frost|Lissandra}}, creating a cold pulse around you in {{tip|cr|icononly=true}} 450 radius that {{tip|root|roots}} nearby enemies for {{fd|1.25}} seconds ({{sti|{{fd|6.5}} seconds cooldown}}).', tier = 'Silver', notes = NULL WHERE name = 'Frost Wraith';
UPDATE augments SET description = 'Replaces {{si|Flee}} with ''''{{si|Frozen Foundations}}''''.<br><br>[[File:Crystallized Will augment spell.png|20px|link=]] {{sbc|Frozen Foundations:}} {{#invoke:SpellData|geteffect|Frozen Foundations}}', tier = 'Silver', notes = NULL WHERE name = 'Frozen Foundations';
UPDATE augments SET description = 'Increase the effects of [[File:Power FlowerSquare.png|20px|link=Arena#Power Flowers|An icon representing the Power Flower plant]] ''''[[Arena#Power Flowers|Power Flowers]]''''. When you hit a ''''Power Flower'''', your teammate gains its effects as well regardless of range and you both gain {{sti|{{as|40% ''''''bonus'''''' movement speed}}}} for 2 seconds.', tier = 'Silver', notes = '* When you share a ''''Power Flower'''' with your teammate, they will neither benefit from your nor their increased ''''Power Flower'''' effect.
			* The increased ''''Power Flower'''' effect {{tip|stacks additively}} with {{tt|{{iis|Guardian''s Dirk}}|Starter items gone}} {{nie|Agricultural Reaper}} for a total of {{pp|type=augment level|40%;60%}} increased ''''Power Flower'''' effectiveness.' WHERE name = 'Fruits of Your Labor';
UPDATE augments SET description = 'Gain {{g|1000}}. Additionally, in your Shop, the cost of {{ii|Prismatic Item|Prismatic Item Anvils}}, all {{ii|Legendary Fighter Item|icononly=true}}{{ii|Legendary Marksman Item|icononly=true}}{{ii|Legendary Assassin Item|icononly=true}}{{ii|Legendary Mage Item|icononly=true}}{{ii|Legendary Tank Item|icononly=true}}{{ii|Legendary Support Item|icononly=true}} Legendary Item Anvils and {{ii|Stat Bonus|Stat Bonus Anvils}} is reduced. The resale value of all ''''Prismatic items'''' and ''''Legendary items'''' is also reduced.', tier = 'Prismatic', notes = '* You will keep Gamba Anvils discounts even after losing the Augment.{{bug}}' WHERE name = 'Gamba Anvil';
UPDATE augments SET description = 'Become tiny, reducing your {{sti|size}} and gaining {{sti|{{as|''''''bonus'''''' movement speed}}}}. Additionally, deal ''''''bonus'''''' damage against enemy champions with greater [[size]] than you.', tier = 'Prismatic', notes = NULL WHERE name = 'Giant Slayer';
UPDATE augments SET description = 'Grants {{sti|{{as|''''''bonus maximum'''''' health}}}}, {{tip|adaptive force}} and {{sti|size}}.', tier = 'Prismatic', notes = NULL WHERE name = 'Goliath';
UPDATE augments SET description = 'Gain {{sti|{{as|omnivamp}}}}.', tier = 'Silver', notes = NULL WHERE name = 'Goredrink';
UPDATE augments SET description = '{{tip|Immobilize|Immobilizing}} or {{tip|ground|grounding}} an enemy champion {{tip|heal|heals}} you ({{sti|5 seconds cooldown}} per {{tip|cast instance}}).', tier = 'Silver', notes = NULL WHERE name = 'Guilty Pleasure';
UPDATE augments SET description = 'Basic attacks deal {{as|''''''bonus'''''' physical damage}} equal to {{sti|{{as|a percentage of your ''''''maximum'''''' health}}}}.', tier = 'Silver', notes = '* ''''''Heavy Hitter'''''' is not and does not interact with {{tip|on-hit}} effects.
		* ''''''Heavy Hitter'''''' deals {{tip|proc damage}}.' WHERE name = 'Heavy Hitter';
UPDATE augments SET description = 'Gain an improved version of {{cai|Guerrilla Warfare|Teemo}}.<br><br>{{sbc|Guerrilla Warfare:}} Gain {{tip|invisibility}} after {{fd|0.75}} seconds without moving, being {{tip|immobilize|immobilized}}, taking damage, performing actions that {{tip|break stealth}}, {{tip|channel|channeling}}, or being in {{tip|stasis (buff)|stasis}}. Upon exiting stealth, gain {{sti|{{as|{{pp|key=%|20 to 80 for 4|1;5;10;15}} ''''''bonus'''''' attack speed}}}} for 5 seconds and {{sti|{{as|100% ''''''bonus'''''' movement speed}}}} decaying over the same duration. Your next attack after exiting stealth deals {{pp|60 to 200|color=magic damage}} {{as|(+ 60% ''''''bonus'''''' AD)}} {{as|(+ 40% AP)}} {{as|''''''bonus'''''' magic damage}}.<br><br>''''Invisibility is granted immediately at the start of the combat phase.''''', tier = 'Silver', notes = NULL WHERE name = 'Hold Very Still';
UPDATE augments SET description = 'Your {{tip|heals}} and {{tip|shields}} cause you to fire a missile to the nearest enemy champion within {{tip|cr|icononly=true}} 650 units over {{fd|0.32}} seconds, applying a {{as|Burn}} upon arrival that deals {{as|magic damage}} based on {{sti|{{as|the target''s ''''''maximum'''''' health}}}} over time.<br><br>The {{as|Burn''s}} per-tick damage increases based on the relative value of the triggering {{tip|heal}} or {{tip|shield}} against the {{sti|{{as|''''''maximum'''''' health}}}} of the ally recipient.<br><br>This counts as a {{as|Burn}} source.', tier = 'Gold', notes = NULL WHERE name = 'Holy Fire';
UPDATE augments SET description = 'Gain {{sti|{{as|''''''bonus'''''' movement speed}}}}. This bonus is lost for 3 seconds after dealing damage to or taking damage from champions.', tier = 'Silver', notes = NULL WHERE name = 'Homeguard';
UPDATE augments SET description = 'Your {{tip|slow|slowing}} effects reduce the {{sti|{{as|movement speed}}}} of targets by an additional amount.', tier = 'Silver', notes = NULL WHERE name = 'Ice Cold';
UPDATE augments SET description = 'Gain the {{ri|Aftershock}} and {{ri|Glacial Augment}} keystone runes.', tier = 'Gold', notes = NULL WHERE name = 'Impassable';
UPDATE augments SET description = 'Your ability hits apply a {{as|Burn}} for 5 seconds that deals persistent {{as|magic damage}} ({{sti|1 second cooldown}} per {{tip|cast instance}}). This {{as|Burn}} stacks infinitely and refreshes with each application. Damage over time abilities can apply the effect only once every 2 seconds.<br><br>Additionally, all of your {{as|Burn}} effects reduce the {{sti|cooldowns}} of all your basic abilities for each tick of damage they deal to a target.<br><br>This counts as a {{as|Burn}} source.', tier = 'Prismatic', notes = NULL WHERE name = 'Infernal Conduit';
UPDATE augments SET description = 'Grants the {{bi|Infernal Dragon Soul}}, or a different {{bi|Dragon Soul}} if one is already obtained.', tier = 'Silver', notes = NULL WHERE name = 'Infernal Soul';
UPDATE augments SET description = 'Grants {{sti|{{as|critical strike chance}}}}.', tier = 'Gold', notes = NULL WHERE name = 'It''s Critical';
UPDATE augments SET description = 'Upon casting your ultimate ability, you apply {{cai|Death Mark|Zed}} to all enemy champions ({{sti|8 seconds cooldown}}). The mark stores a percentage of all {{tt|post-mitigation|Damage calculated before modifiers}} damage dealt to the affected target, detonating after 5 seconds to deal {{sti|{{as|true damage}}}} equal to the damage stored against them.<br><br>If this augment''s cooldown elapses during the channel of {{cai|Crowstorm|Fiddlesticks}}, {{cai|Hero''s Entrance|Galio}} or {{cai|Grand Starfall|Pantheon}}, this effect activates right before their first respective damaging effect activates.', tier = 'Gold', notes = '* The damage from ''''''It''s Killing Time'''''' benefits from ultimate damage modifiers.' WHERE name = 'It''s Killing Time';
UPDATE augments SET description = 'Your abilities can now {{tip|critical strike|critically strike}} to deal higher damage. Additionally, gain {{sti|{{as|critical strike chance}}}} based on your {{sti|{{as|ability power}}}}.<br><br>If both ''''Jeweled Gauntlet'''' and [[File:Vulnerability ar augment.png|20px|link=|An icon for the Arena augment Vulnerability]] ''''Vulnerability'''' are equipped, only rolls the {{sti|{{as|critical strike chance}}}} of the augment that has the higher {{sti|{{as|critical damage}}}} (or either if equal).', tier = 'Prismatic', notes = NULL WHERE name = 'Jeweled Gauntlet';
UPDATE augments SET description = 'Each round, you and your ally gain several ''''Juices'''' ({{ii|Cappa Juice|icononly=true}} {{ii|Juice of Haste|icononly=true}} {{ii|Juice of Power|icononly=true}} {{ii|Juice of Vitality|icononly=true}}) for free that is automatically consumed at the start of the combat phase.', tier = 'Silver', notes = NULL WHERE name = 'Juice Box';
UPDATE augments SET description = 'Gain the {{ri|Arcane Comet}} and {{ri|Summon Aery}} keystone runes.<br><br>''''See [[Arena#Runes]] for Arena-specific overrides on {{ri|Summon Aery}}.''''', tier = 'Gold', notes = NULL WHERE name = 'Keystone Conjurer';
UPDATE augments SET description = 'Continuously fire a laser in a line 700 units from your facing direction, dealing {{as|{{pp|5 to 60}}|magic damage}} {{as|(+ {{ap|56/4}}% AD)}} {{as|(+ {{ap|36/4}}% AP)}} {{as|magic damage}} every {{fd|0.25}} seconds to enemies in its width of 80 units.', tier = 'Prismatic', notes = NULL WHERE name = 'Laser Eyes';
UPDATE augments SET description = 'Basic attacks {{tip|on-hit}} generate a stack, up to 4. The fourth stack consumes them all to quickly launch 4 fireworks at the target that deal {{as|{{pp|11 to 80}}|magic damage}} {{tip|on-hit}}.', tier = 'Silver', notes = NULL WHERE name = 'Light ''em Up!';
UPDATE augments SET description = '{{as|Automatically}} cast {{cai|Prismatic Barrier|Lux}}, throwing a warding light towards your ally which grants a {{tip|shield}} for {{pp|25+3*x}} {{as|(+ {{fd|7.5}}% ''''''bonus'''''' AD)}} {{as|(+ 20% AP)}} to you and your ally for {{fd|2.5}} seconds upon coming into contact with it. After reaching maximum range, the light then homes back to you to grant the same shield again when it passes through you and your ally, stacking with the previous shield and refreshing its duration ({{sti|8 seconds cooldown}}).', tier = 'Gold', notes = NULL WHERE name = 'Light Warden';
UPDATE augments SET description = 'Increase your {{sti|{{as|''''''bonus'''''' attack speed}}}} gained from all sources. While at {{sti|as|{{as|{{fd|3.0}}|as}}}} attack speed or higher, your basic attacks deal {{as|40 ''''''bonus'''''' magic damage}} {{tip|on-hit}}.', tier = 'Gold', notes = NULL WHERE name = 'Lightning Strikes';
UPDATE augments SET description = 'At the start of the combat phase in each round, gain either 30% {{tip|adaptive force}}, {{sti|{{as|''''''bonus'''''' health}}}} and {{sti|40% increased size}}, or {{sti|{{as|ability haste}}}}, {{sti|{{as|40% ''''''bonus'''''' movement speed}}}} and {{sti|40% reduced size}}.', tier = 'Prismatic', notes = NULL WHERE name = 'Mad Scientist';
UPDATE augments SET description = 'Dealing damage to an enemy with an ability within {{tip|cr|icononly=true}} 1000 units fires several missiles at them that each deal {{as|true damage}} equal to {{as|{{fd|0.3{{recurring|3}}}}% of the target''s ''''''maximum'''''' health}}, increased to up to {{as|1%|health}} based on distance travelled. This effect can only trigger once every 6 seconds from the same cast.', tier = 'Gold', notes = NULL WHERE name = 'Magic Missile';
UPDATE augments SET description = 'Basic attacks deal {{as|''''''bonus'''''' physical damage}} based on your {{sti|{{as|ability power}}}}.', tier = 'Gold', notes = '* ''''''Marksmage'''''' is not and does not interact with {{tip|on-hit}} effects.
		* ''''''Marksmage'''''' deals {{tip|proc damage}}.' WHERE name = 'Marksmage';
UPDATE augments SET description = 'Basic attacks {{tip|on-hit}} grant {{sti|{{as|{{pp|6 to 18}} ability power}}}} and ability casts grant {{sti|{{as|{{pp|3 to 9}} ''''''bonus'''''' attack damage}}}}. This effect stacks infinitely and lasts until the end of the current round phase.', tier = 'Prismatic', notes = NULL WHERE name = 'Master of Duality';
UPDATE augments SET description = 'Grants {{sti|{{as|''''''bonus'''''' health}}}} equal to a percentage of {{sti|{{as|your ''''''maximum'''''' mana}}}}.', tier = 'Silver', notes = NULL WHERE name = 'Mind to Matter';
UPDATE augments SET description = 'Your {{tip|pet|pets}} deal increased damage as well as gain {{sti|{{as|''''''bonus'''''' health}}}} and {{sti|size}}.', tier = 'Gold', notes = NULL WHERE name = 'Minionmancer';
UPDATE augments SET description = 'Gain an improved version of {{cai|Mirror Image|LeBlanc}}.<br><br>{{sbc|Mirror Image:}} Upon being damaged to {{sti|{{as|30% ''''''maximum'''''' health}}}}, create 4 {{tip|clone|clones}} of yourself, after which you and your clones instantly become {{tip|invisible}} for {{fd|1.25}} seconds ({{sti|30 seconds cooldown}}). Your clones can mimic your [[basic attack]] animation, though cannot deal damage and last for 8 seconds. One clone may move in front of you, the others will move toward random directions. ''''Clones have a {{g|25}} bounty.''''', tier = 'Silver', notes = NULL WHERE name = 'Mirror Image';
UPDATE augments SET description = 'Grants the {{bi|Mountain Dragon Soul}}, or a different {{bi|Dragon Soul}} if one is already obtained.', tier = 'Silver', notes = NULL WHERE name = 'Mountain Soul';
UPDATE augments SET description = 'Basic attacks {{tip|on-hit}} reduce the remaining cooldowns of your abilities by {{sti|cooldown|{{fd|1.25}} seconds}}.', tier = 'Prismatic', notes = NULL WHERE name = 'Mystic Punch';
UPDATE augments SET description = 'Upon taking fatal damage, you enter a [[Arena#Revival|downed state]] as normal but modify the arm time for the revive and automatically revive yourself without the help of your ally over 8 seconds. Additionally, you can enter the downed state for revival an additional time after the first revive, for a total of 2 revives per round. Each time you revive however, you respawn with reduced {{sti|{{as|''''''maximum'''''' health}}}} and {{sti|size}}. The first revive reduces your {{sti|{{as|''''''maximum'''''' health}}}} by {{as|20%|hp}} and {{sti|size}} by 20% and the second does so by {{as|36%|hp}} and 40% ({{as|80% ''''''total maximum'''''' health}} and 80% size for first revive, then {{as|64% ''''''total maximum'''''' health}} and 60% size for the second), and so on.<br><br>This effect only activates while your ally is alive and is cancelled immediately if they die while you are in the downed state. You and your ally can enter the downed state even after one of you has already been revived from one, though not a second time for your ally. If your ally stands in your revival zone, the revive occurs faster. Upon reviving, you {{tip|airborne|knock back}} all nearby enemies.', tier = 'Prismatic', notes = NULL WHERE name = 'Nesting Doll';
UPDATE augments SET description = 'Replaces {{si|Flee}} with ''''{{si|Now You See Me}}''''.<br><br>[[File:Now You See Me augment spell.png|20px|link=]] {{sbc|Now You See Me:}}<br><br>{{#invoke:SpellData|geteffect|Now You See Me}}<br><br>{{#invoke:SpellData|geteffect2|Now You See Me}}', tier = 'Silver', notes = '* You can decide which portal to teleport to by moving your mouse cursor to that portal.' WHERE name = 'Now You See Me';
UPDATE augments SET description = 'Replaces {{si|Flee}} with ''''{{cai|Fate''s Call|Kalista}}''''.<br><br>{{sbc|Fate''s Call:}} Retrieve your ally and hold them for 4 seconds, {{tip|dash|pulling}} them to yourself over 1 second and {{tip|cleanse|cleansing}} them from all {{tip|crowd control}}, as well as rendering them {{tip|invulnerable}} and {{tip|untargetable}} for the duration ({{sti|60 seconds cooldown}}).<br><br>While being held, your ally is {{tip|vanish|vanished}} and can {{tip|dash}} with {{tip|displacement immunity}} to end ''''Fate''s Call''s'''' effects and reappear at the target location; after the duration, they will automatically do so at maximum range from your facing direction. The ally''s dash stops upon colliding with an enemy {{tip|champion}}, {{tip|airborne|knocking}} up all nearby enemies briefly and landing to their {{sti|attack range|{{as|''''''base'''''' attack range}}}} from the target collided with.', tier = 'Gold', notes = NULL WHERE name = 'Oathsworn';
UPDATE augments SET description = 'Grants the {{bi|Ocean Dragon Soul}}, which has a modified base {{tip|heal}} value of 100, or a different {{bi|Dragon Soul}} if one is already obtained.', tier = 'Silver', notes = NULL WHERE name = 'Ocean Soul';
UPDATE augments SET description = '{{as|Automatically}} cast {{cai|Boomerang Blade|Sivir}} at a nearby enemy, dealing {{as|physical damage}} to enemies hit ({{sti|7 seconds cooldown}}).', tier = 'Gold', notes = NULL WHERE name = 'OK Boomerang';
UPDATE augments SET description = 'Grants random {{bi|Dragon Soul|Dragon Souls}}.', tier = 'Prismatic', notes = NULL WHERE name = 'Omni Soul';
UPDATE augments SET description = 'Replaces {{si|Flee}} with ''''{{si|Orbital Laser}}''''.<br><br>[[File:Orbital Laser augment spell.png|20px|link=]] {{sbc|Orbital Laser:}} {{#invoke:SpellData|geteffect|Orbital Laser}}', tier = 'Prismatic', notes = NULL WHERE name = 'Orbital Laser';
UPDATE augments SET description = '{{tip|Dash|Dashing}} or {{tip|blink|blinking}} grants {{sti|{{as|''''''bonus'''''' armor}}}} and {{sti|{{as|''''''bonus'''''' magic resistance}}}}, stacking up to 5 times. This effect lasts until the end of the current round phase.', tier = 'Gold', notes = NULL WHERE name = 'Outlaw''s Grit';
UPDATE augments SET description = 'You {{tip|heal}} for a part of the damage dealt by your ally.', tier = 'Gold', notes = NULL WHERE name = 'Parasitic Relationship';
UPDATE augments SET description = 'Grants a great amount of {{sti|health regeneration|{{as|''''''base'''''' health regeneration}}}}, increased while below {{sti|{{as|a certain health threshold}}}}.', tier = 'Gold', notes = NULL WHERE name = 'Perseverance';
UPDATE augments SET description = 'Gain {{cai|Phenomenal Evil Power|Veigar}}.<br><br>{{sbc|Phenomenal Evil Power:}} Generate a permanent stack of ''''Phenomenal Evil'''' each time you damage an enemy champion with {{tip|ability damage}}. This effect cannot trigger more than once every second globally and once every 5 seconds from the same {{tip|cast instance}}. For each stack, gain {{sti|{{as|ability power}}}}.<br><br>If this is your second augment, start with 40 ''''Phenomenal Evil'''' stacks, granting you {{sti|{{as|40 ability power}}}}.', tier = 'Gold', notes = NULL WHERE name = 'Phenomenal Evil';
UPDATE augments SET description = 'Scoring a champion {{tip|takedown}} generates a stack, once per champion per round. This augment will transform into a free {{ii|Prismatic Item|Prismatic Item Anvil}}, a Prismatic Augment selection and a free {{ii|Stat Bonus|Prismatic Stat Anvil}} at 5 stacks.<br><br>''''These bonuses are granted at the start of the shop phase after a combat phase where the stack requirement is achieved.''''', tier = 'Prismatic', notes = NULL WHERE name = 'Prismatic Egg';
UPDATE augments SET description = '{{as|Automatically}} cast an improved version of {{cai|Tactical Sweep|Camille}}, winding over {{fd|0.75}} seconds to slash in a 650 radius around you. The slash deals {{as|physical damage}} to enemies within the area ({{sti|12 seconds cooldown}}). Enemies hit by the outer edge of the circle take {{as|''''''bonus'''''' physical damage}} equal to {{as|10%|hp}} {{as|(+ {{fd|2.5}}% per 100 ''''''bonus'''''' AD)}} {{as|(+ {{fd|1.6}}% per 100 AP)}} {{as|(+ {{fd|0.1}}% per 100 ''''''bonus'''''' health)}} {{as|of their ''''''maximum'''''' health}} and are {{tip|slow|slowed}} decaying over 2 seconds. Additionally, you are {{tip|heal|healed}} for a part of the ''''''bonus'''''' {{tt|post-mitigation|Damage calculated after modifiers}} damage against enemy champions hit by the outer edge.', tier = 'Prismatic', notes = NULL WHERE name = 'Quantum Computing';
UPDATE augments SET description = '{{sbc|Quest:}} {{tip|Heal}} allied champions for 2500 in total, or mitigate 2500 damage for them.<br><br>{{sbc|Reward:}} Upon completing your {{sbc|Quest}}, gain {{sti|{{as|100% ''''''bonus'''''' attack speed}}}} and empower your basic attacks to deal {{as|''''''bonus'''''' magic damage}} equal to {{sti|{{as|350% of your heal and shield power}}}}.', tier = 'Gold', notes = NULL WHERE name = 'Quest: Angel of Retribution';
UPDATE augments SET description = '{{sbc|Quest:}} Obtain {{ii|Heartsteel}} and accumulate over {{as|400 ''''''bonus'''''' health}} from ''''Colossal Consumption''''.<br><br>{{sbc|Reward:}} Upon completing your {{sbc|Quest}}, increase the {{as|''''''bonus'''''' health}} previously and future gained from {{iis|Heartsteel}} ''''Colossal Consumption'''' by 300%, and gain {{sti|{{as|''''''bonus'''''' health regeneration}}}} equal to {{as|{{fd|12.5}}% of the ''''''bonus'''''' health}} gained from ''''Colossal Consumption''''.', tier = 'Gold', notes = NULL WHERE name = 'Quest: Steel Your Heart';
UPDATE augments SET description = '{{sbc|Quest:}} Score 8 champion {{tip|takedown|takedowns}}, up to one for each enemy per round.<br><br>{{sbc|Reward:}} Upon completing your {{sbc|Quest}}, you receive {{ii|The Golden Spatula}}.<br><br>{{ii|The Golden Spatula}} counts as a {{as|Burn}} source.', tier = 'Gold', notes = '* Getting takedowns by hitting tomatoes from Kled GOH count towards the takedown goal.' WHERE name = 'Quest: Urf''s Champion';
UPDATE augments SET description = 'Gain a {{ii|Needlessly Large Rod}} that has its {{as|ability power}} stat modified to {{sti|{{as|120 AP}}}}.<br><br>{{sbc|Quest:}} Obtain {{ii|Rabadon''s Deathcap}} and {{ii|Zhonya''s Hourglass}}.<br><br>{{sbc|Reward:}} Upon completing your {{sbc|Quest}}, convert the items you obtained for the quest into {{ii|Wooglet''s Witchcap}}.', tier = 'Prismatic', notes = NULL WHERE name = 'Quest: Wooglet''s Witchcap';
UPDATE augments SET description = 'Casting an ability {{tip|heal|heals}} you, based on your {{sti|{{as|''''''maximum'''''' health}}}}.', tier = 'Gold', notes = NULL WHERE name = 'Rabble Rousing';
UPDATE augments SET description = 'At the start of the combat phase in each round, you are now imprisoned in the center of the battlefield for 9 seconds, becoming {{tip|suppression|suppressed}} in the duration. While imprisoned, you gain {{pp|key=%|type=current round|40 to 70 for 11|1;2;3;4;5;6;7;8;9;10;11+}} damage reduction (including against {{sti|{{as|true damage}}}}) and {{tip|cc-immune|crowd control immunity}}, and increase your {{sti|{{as|attack damage}}}}, {{sti|{{as|ability power}}}}, {{sti|{{as|''''''maximum'''''' health}}}}, and {{sti|size}} according to the time you''re imprisoned.<br><br>At the end of the duration, or upon being damaged to {{as|50% ''''''maximum'''''' health}} otherwise, you are set free, {{tip|airborne|knocking back}} all nearby enemies and losing the damage reduction and crowd control immunity but keeping the other bonuses until the end of the round. Additionally, you receive a {{tip|shield}} that absorbs damage equal to {{sti|{{as|a percentage of your ''''''maximum'''''' health}}}} and lasts until destroyed.', tier = 'Prismatic', notes = NULL WHERE name = 'Raid Boss';
UPDATE augments SET description = 'Grants {{sti|{{as|ability haste}}}}.', tier = 'Gold', notes = NULL WHERE name = 'Recursion';
UPDATE augments SET description = 'Upon dropping below {{sti|health|{{as|60%|health}}}} or {{as|30% of your ''''''maximum'''''' health}}, each for the first time in a round, {{tip|airborne|knock back}} all enemies within a {{tip|cr|icononly=true}} 500 radius by 750 units.', tier = 'Silver', notes = '* The {{tip|airborne}} status effect from the knock back does not interrupt {{tip|channel|channels}} nor disable {{tip|ability|abilities}}.{{bug}}
        ** It will still seal the target''s movement-based summoner spells.' WHERE name = 'Repulsor';
UPDATE augments SET description = '{{as|Automatically}} refresh your basic abilities'' cooldowns {{sti|cooldown|every several seconds}}.', tier = 'Gold', notes = NULL WHERE name = 'Restart';
UPDATE augments SET description = 'You constantly {{tip|heal}} while moving.', tier = 'Gold', notes = NULL WHERE name = 'Restless Restoration';
UPDATE augments SET description = 'Gain {{sti|attack range|{{rd|75|50}} ''''''bonus'''''' attack range}}.<br><br>''''Removed since [[V26.09]].''''', tier = 'Silver', notes = NULL WHERE name = 'Scoped Weapons';
UPDATE augments SET description = 'Gain {{sti|attack range|{{rd|200|100}} ''''''bonus'''''' attack range}}.<br><br>''''Removed since [[V26.09]].''''', tier = 'Gold', notes = NULL WHERE name = 'Scopier Weapons';
UPDATE augments SET description = 'Gain {{sti|attack range|''''''bonus'''''' attack range}}.', tier = 'Prismatic', notes = NULL WHERE name = 'Scopiest Weapons';
UPDATE augments SET description = 'Gain {{cai|Sunlight|Leona}}.<br><br>{{sbc|Sunlight:}} Your abilities mark enemies, causing them to take {{as|''''''bonus'''''' magic damage}} based on {{sti|{{as|their ''''''maximum'''''' health}}}} from your ally''s next basic attack or ability hit against them ({{sti|{{fd|0.75}}-second cooldown}} per target).', tier = 'Gold', notes = NULL WHERE name = 'Searing Dawn';
UPDATE augments SET description = '{{as|Automatically}} get a bomb attached to you that detonates after {{sti|cooldown|15 seconds}}, creating an explosion that deals {{as|true damage}} based on {{as|the target''s ''''''maximum'''''' health}} to enemies within 350 units and {{tip|airborne|knocks them up}} for {{fd|0.75}} seconds ({{sti|15 seconds cooldown}}).<br><br>The bomb''s duration is not refreshed when the initial delay for the combat phase elapses.', tier = 'Silver', notes = '* The {{tip|airborne}} status effect from the knock up does not interrupt {{tip|channel|channels}} nor disable {{tip|ability|abilities}}, and is not resisted by {{tip|cc-immune|immunity}} nor {{tip|spell shield}}.{{bug}}' WHERE name = 'Self Destruct';
UPDATE augments SET description = 'Upon taking fatal damage for the first time, you are restored to {{as|100% ''''''maximum'''''' health}} but suffer {{as|true damage}} over time until you die from reaching 0 health. Scoring a champion {{tip|takedown}} ends this effect''s damage immediately and sets your {{sti|{{as|''''''current'''''' health}}}} to {{as|a percentage of ''''''maximum'''''' health}}.', tier = 'Silver', notes = NULL WHERE name = 'Serve Beyond Death';
UPDATE augments SET description = 'After {{tip|dash|dashing}}, {{tip|blink|blinking}}, or exiting {{tip|stealth}}, gain {{sti|{{as|''''''bonus'''''' movement speed}}}} for a period of time.', tier = 'Silver', notes = NULL WHERE name = 'Shadow Runner';
UPDATE augments SET description = 'Basic attacks reduce the target''s damage dealt for 3 seconds, refreshing with each hit. Their {{sti|size}} is also reduced significantly for the duration.', tier = 'Gold', notes = NULL WHERE name = 'Shrink Ray';
UPDATE augments SET description = 'Hitting an enemy with a basic ability while located at least {{tip|er|icononly=true}} 700 units away from them at the time of the hit {{sti|cooldown|reduces the ''''''current'''''' cooldown}} of that ability to {{fd|0.5}} seconds. If the ability hit is from a damage over time effect, the cooldown of the ability is instead reduced to 3 seconds if it is not already below that.', tier = 'Gold', notes = NULL WHERE name = 'Skilled Sniper';
UPDATE augments SET description = '{{tip|Immobilize|Immobilizing}} or {{tip|ground|grounding}} an enemy champion grants you {{tip|adaptive force}}, stacking infinitely ({{sti|5 seconds cooldown}} per {{tip|cast instance}}). This effect lasts until the end of the current round phase.', tier = 'Silver', notes = NULL WHERE name = 'Slap Around';
UPDATE augments SET description = '{{as|Automatically}} cast {{cai|Unstable Matter|Zac}}, releasing a burst of slime in a {{tip|cr|icononly=true}} 450 radius around you and dealing {{as|{{pp|40 to 80}}|magic damage}} {{as|(+ {{pp|3 to 7|key=%}} {{as|(+ {{fd|1.5}}% per 100 ''''''bonus'''''' AD)}} {{as|(+ {{fd|1.5}}% per 100 AP)}} of target''s ''''''maximum'''''' health)}} {{as|magic damage}} to enemies hit ({{sti|7 seconds cooldown}}). Additionally, hitting a champion secretes a slime blob toward a nearby location. Both you and enemy champions can interact with the blob by moving over it; you may consume it to {{tip|heal}} yourself for {{as|{{pp|3 to 6|key=%}} of your ''''''maximum'''''' health}}, while an enemy may destroy it to deny the effect.', tier = 'Silver', notes = NULL WHERE name = 'Slime Time';
UPDATE augments SET description = 'Surrounds you in flames, causing you to apply a {{as|Burn}} every second to enemies within {{tip|cr|icononly=true}} 500 units for 5 seconds that deals {{as|magic damage}}. This {{as|Burn}} stacks infinitely and refreshes with each application.<br><br>This counts as a {{as|Burn}} source.', tier = 'Prismatic', notes = NULL WHERE name = 'Slow Cooker';
UPDATE augments SET description = 'Replaces {{si|Flee}} with ''''{{si|Mark}}'''' / ''''{{si|Dash}}''''.<br><br>{{sbc|Mark:}} Throws a snowball in the target direction that deals {{as|{{pp|15 to 100}} true damage}} to the first enemy hit and marks them for 3 seconds ({{sti|6 seconds cooldown}}). While the target is marked, you are granted the ability to cast {{si|Dash}}.<br><br>{{sbc|Dash:}} You {{tip|dash}} to the marked target while being {{tip|untargetable}}, dealing the same damage again upon arrival.', tier = 'Silver', notes = NULL WHERE name = 'Snowball Fight!';
UPDATE augments SET description = 'Granting a [[buff]], {{tip|heal}}, or {{tip|shield}} to your ally deals {{as|{{pp|30 to 150}} true damage}} to enemies within 450 units of them and {{tip|slow|slows}} targets by 30% ({{sti|2 seconds cooldown}}).', tier = 'Silver', notes = NULL WHERE name = 'Sonic Boom';
UPDATE augments SET description = 'Your {{tip|critical strike|critical strikes}} {{tip|heal}} you for a part of damage dealt. Additionally, gain {{as|25% critical strike chance}}.', tier = 'Gold', notes = NULL WHERE name = 'Soul Siphon';
UPDATE augments SET description = 'Hitting an enemy champion with an ability sends a trail centered from you to the location they were hit, detonating in a 100 width radius after {{fd|0.75}} seconds to deal {{as|magic damage}} to enemies within. This effect can only trigger once every 6 seconds from the same cast.', tier = 'Prismatic', notes = NULL WHERE name = 'Spellwake';
UPDATE augments SET description = 'Your {{tt|spinning abilities|Any ability with ''spinning'' properties}} deal increased damage and benefit from {{sti|{{as|ability haste}}}}.', tier = 'Silver', notes = NULL WHERE name = 'Spin To Win';
UPDATE augments SET description = 'Redirect a part of the damage dealt to your ally to you, and {{tip|heal}} yourself equal to a part of the healing they receive.', tier = 'Prismatic', notes = NULL WHERE name = 'Spirit Link';
UPDATE augments SET description = 'Increase the number of permanent stacks you gain from abilities by 75%.', tier = 'Silver', notes = NULL WHERE name = 'Stackosaurus Rex';
UPDATE augments SET description = 'Upon selecting this augment, gain {{ii|Stat Bonus|Stat Bonus Anvils}} for free.', tier = 'Silver', notes = NULL WHERE name = 'Stats!';
UPDATE augments SET description = 'Upon selecting this augment, gain {{ii|Stat Bonus|Stat Bonus Anvils}} for free.', tier = 'Gold', notes = NULL WHERE name = 'Stats on Stats!';
UPDATE augments SET description = 'Upon selecting this augment, gain {{ii|Stat Bonus|Stat Bonus Anvils}} for free.', tier = 'Prismatic', notes = NULL WHERE name = 'Stats on Stats on Stats!';
UPDATE augments SET description = 'The first several times you use each unique summoner spell in the current phase of the round, set its cooldown to {{sti|cooldown|3 seconds}} instead of its default. Additionally, the {{sti|cooldown}} of your {{si|Flash}} resets every round.', tier = 'Gold', notes = NULL WHERE name = 'Summoner Revolution';
UPDATE augments SET description = 'Replace both of your summoner spells with random ones available in a pool. After using a summoner spell during the combat phase, replace the spell in the respective slot with another random one.<br><br>{{sbc|Summoner Spell Pool:}} {{si|Banner of Command}}, {{si|Barrier}}, {{si|Blade Waltz}}, {{si|Castle}}, {{si|Cleanse}}, {{si|Mark}} / {{si|Dash}}, {{si|Defensive Maneuvers}}, {{si|Die Another Day}}, {{si|Exhaust}}, {{si|Feel the Burn}}, {{si|Flash}}, {{si|Flee}}, {{si|Ghost}}, {{si|Heal}}, {{si|Ignite}}, {{si|Vanish}}', tier = 'Prismatic', notes = NULL WHERE name = 'Summoner''s Roulette';
UPDATE augments SET description = 'Gain the {{ri|Conqueror}} and {{ri|Lethal Tempo}} keystone runes.<br><br>''''See [[Arena#Runes]] for Arena-specific overrides on these keystones.''''', tier = 'Prismatic', notes = '* {{ri|Lethal Tempo}} at max stack sets {{sti|attack speed|{{as|attack speed cap}}}} to {{as|10|as}}.' WHERE name = 'Symphony of War';
UPDATE augments SET description = 'Gain ''''Critical Defend Chance'''' equal to {{sti|{{as|100% of your critical strike chance}}}}, up to {{sti|50%|critical strike chance}}. Additionally, gain {{sti|{{as|25% critical strike chance}}}}.<br><br>{{sbc|Critical Defend Chance:}} Grants you a chance to reduce an instance of damage taken.', tier = 'Silver', notes = NULL WHERE name = 'Tank It Or Leave It';
UPDATE augments SET description = 'Basic attacks {{tip|on-hit}} grant {{sti|{{as|''''''bonus'''''' movement speed}}}}, stacking infinitely and lasting until the end of the current round phase. Additionally, gain {{sti|{{as|''''''bonus'''''' attack speed}}}} equal to {{sti|{{as|10% of your ''''''total'''''' movement speed}}}}.', tier = 'Prismatic', notes = NULL WHERE name = 'Tap Dancer';
UPDATE augments SET description = 'Grants {{sti|{{as|''''''bonus'''''' attack damage}}}}, {{sti|{{as|ability haste}}}}, and {{sti|{{as|lethality}}}}.', tier = 'Silver', notes = NULL WHERE name = 'The Brutalizer';
UPDATE augments SET description = 'Grants {{sti|{{as|armor penetration}}}} and {{sti|{{as|magic penetration}}}}.', tier = 'Gold', notes = NULL WHERE name = 'Thread the Needle';
UPDATE augments SET description = '{{tip|Immobilize|Immobilizing}} or {{tip|ground|grounding}} an enemy champion inflicts them with a {{as|Burn}} for 5 seconds, dealing {{as|magic damage}} based on {{sti|{{as|the target''s ''''''maximum'''''' health}}}} ({{sti|5 seconds cooldown}} per {{tip|cast instance}}). This {{as|Burn}} stacks infinitely and refreshes with each application.<br><br>This counts as a {{as|Burn}} source.', tier = 'Silver', notes = NULL WHERE name = 'Tormentor';
UPDATE augments SET description = '{{tip|Dash|Dashing}} or {{tip|blink|blinking}} causes you to inflict the nearest enemy champion within {{tip|cr|icononly=true}} 650 units with a {{as|Burn}} for 5 seconds, dealing {{as|magic damage}} based on {{sti|{{as|the target''s ''''''maximum'''''' health}}}} ({{sti|{{fd|1.5}} seconds cooldown}} per {{tip|cast instance}}). This {{as|Burn}} stacks infinitely and refreshes with each application.<br><br>This counts as a {{as|Burn}} source.', tier = 'Silver', notes = NULL WHERE name = 'Trailblazer';
UPDATE augments SET description = 'Upon damaging an enemy while located at over {{tip|cr|icononly=true}} {{tt|700 units away|center-to-edge}} at the time of the hit, cast {{cai|Trueshot Barrage|Ezreal}} in their direction. The barrage deals {{as|{{pp|175 to 525}}|magic damage}} {{as|(+ 100% ''''''bonus'''''' AD)}} {{as|(+ 70% AP)}} {{as|magic damage}} to enemies it passes through. This augment has {{sti|cooldown}} on each target.', tier = 'Prismatic', notes = NULL WHERE name = 'Trueshot Prodigy';
UPDATE augments SET description = 'Basic attacks generate a stack. At maximum stack, your next basic attack consumes all stacks to apply {{tip|on-hit}} effects again at 100% effectiveness.', tier = 'Gold', notes = NULL WHERE name = 'Twice Thrice';
UPDATE augments SET description = 'Basic attacks fire a bolt at an additional target that deals {{as|physical damage}} and applies on-hit effects at 100% effectiveness.', tier = 'Silver', notes = NULL WHERE name = 'Typhoon';
UPDATE augments SET description = 'Casting your ultimate ability resets its {{sti|cooldown}} immediately after its effect {{tt|starts|For instant-cast spells}} or has {{tt|elapsed|For duration-based spells}}. This may occur only once per phase in a round.', tier = 'Prismatic', notes = NULL WHERE name = 'Ultimate Revolution';
UPDATE augments SET description = 'Replaces {{si|Flee}} with a random champion''s ultimate ability, available from a pool. After using the granted ultimate ability during the combat phase, replace the ultimate in the respective slot with another random one after the cooldown for this effect elapses ({{pp|20 to 15 for 3|1;6;16}} seconds {{tt|cooldown|Affected by ultimate haste}}, increased to {{pp|25 to 20 for 3|1;6;16}} for {{cai|Maximum Dosage|Dr. Mundo}}).<br><br>{{sbc|Ultimate Ability Pool:}} {{cai|Feast|Cho''Gath}}, {{cai|Maximum Dosage|Dr. Mundo}}, {{cai|Cannon Barrage|Gangplank}}, {{cai|Explosive Cask|Gragas}}, {{cai|The Culling|Lucian}}, {{cai|Final Spark|Lux}}, {{cai|Soul Shackles|Morgana}}.<br><br>''''You can receive your own champion''s ultimate ability from this augment. Ultimate abilities granted by this effect count as an ultimate for all purposes.''''', tier = 'Prismatic', notes = NULL WHERE name = 'Ultimate Roulette';
UPDATE augments SET description = 'Casting your ultimate ability grants you {{tip|cc-immune|crowd control immunity}} ({{sti|8 seconds cooldown}}).', tier = 'Silver', notes = NULL WHERE name = 'Ultimate Unstoppable';
UPDATE augments SET description = 'Replaces {{si|Flee}} with ''''{{si|Vanish}}''''.<br><br>[[File:Vanish augment spell.png|20px|link=]] {{sbc|Vanish:}} {{#invoke:SpellData|geteffect|Vanish}}', tier = 'Gold', notes = NULL WHERE name = 'Vanish';
UPDATE augments SET description = 'After your ally dies once, gain increased damage and {{sti|{{as|omnivamp}}}} for the remainder of the round.', tier = 'Gold', notes = NULL WHERE name = 'Vengeance';
UPDATE augments SET description = 'Damage dealt by items and damage over time effects can now {{tip|critical strike|critically strike}} for extra damage. Additionally, gain {{sti|{{as|25% critical strike chance}}}}.<br><br>If both ''''Vulnerability'''' and [[File:Jeweled Gauntlet ar augment.png|20px|link=|An icon for the Arena augment Jeweled Gauntlet]] ''''Jeweled Gauntlet'''' are equipped, only rolls the critical strike chance of the augment that has the higher critical damage (or either if equal).', tier = 'Gold', notes = '* Certain non-damage-over-time abilities will benefit from this augment.{{bug}}
		* ''''Vulnerability'''' now stacks multiplicatively with ''''Jeweled Gauntlet'''' on those non-damage-over-time abilities.{{bug}} On damage-over-time abilities, only one of ''''Vulnerability'''' and ''''Jeweled Gauntlet'''' will take effect.' WHERE name = 'Vulnerability';
UPDATE augments SET description = 'Replaces {{si|Flee}} with ''''{{si|Warmup Routine}}''''.<br><br>[[File:Warmup Routine augment spell.png|20px|link=]] {{sbc|Warmup Routine:}} {{#invoke:SpellData|geteffect|Warmup Routine}}', tier = 'Silver', notes = NULL WHERE name = 'Warmup Routine';
UPDATE augments SET description = 'When your ally drops below {{sti|{{as|30% of their ''''''maximum'''''' health}}}}, reduce your {{sti|{{as|''''''current'''''' health}}}} by {{as|25%|health}} to grant them a {{tip|shield}} equal to {{sti|{{as|a percentage of your ''''''current'''''' health}}}} for 10 seconds.', tier = 'Gold', notes = NULL WHERE name = 'Willing Sacrifice';
UPDATE augments SET description = 'Grants 1 level upon selecting this augment and 1 additional level at the start of every other round. Additionally, the level cap for your champion is removed, allowing them to benefit from effects that scale past level 18, including stat growth.<br><br>If this augment is picked after Round 4, gain 3 levels upon selecting the augment instead of 1.', tier = 'Prismatic', notes = NULL WHERE name = 'Wisdom of Ages';
UPDATE augments SET description = 'Grants {{sti|{{as|ability power}}}}.', tier = 'Silver', notes = NULL WHERE name = 'Witchful Thinking';
UPDATE augments SET description = 'Grants {{sti|{{as|''''''bonus'''''' movement speed}}}} based on your {{sti|{{as|ability haste}}}}.', tier = 'Gold', notes = NULL WHERE name = 'With Haste';

