-- Seed items from frontend/items.json (description omitted for performance)
INSERT INTO items (id, name, description, image) VALUES
(1001, 'Boots', NULL, 'boots.png'),
(1004, 'Faerie Charm', NULL, 'faerie-charm.png'),
(1006, 'Rejuvenation Bead', NULL, 'rejuvenation-bead.png'),
(1011, 'Giant''s Belt', NULL, 'giants-belt.png'),
(1018, 'Cloak of Agility', NULL, 'cloak-of-agility.png'),
(1026, 'Blasting Wand', NULL, 'blasting-wand.png'),
(1027, 'Sapphire Crystal', NULL, 'sapphire-crystal.png'),
(1028, 'Ruby Crystal', NULL, 'ruby-crystal.png'),
(1029, 'Cloth Armor', NULL, 'cloth-armor.png'),
(1031, 'Chain Vest', NULL, 'chain-vest.png'),
(1033, 'Null-Magic Mantle', NULL, 'nullmagic-mantle.png'),
(1035, 'Emberknife', NULL, 'emberknife.png'),
(1036, 'Long Sword', NULL, 'long-sword.png'),
(1037, 'Pickaxe', NULL, 'pickaxe.png'),
(1038, 'B. F. Sword', NULL, 'b-f-sword.png'),
(1039, 'Hailblade', NULL, 'hailblade.png'),
(1040, 'Obsidian Edge', NULL, 'obsidian-edge.png'),
(1042, 'Dagger', NULL, 'dagger.png'),
(1043, 'Recurve Bow', NULL, 'recurve-bow.png'),
(1052, 'Amplifying Tome', NULL, 'amplifying-tome.png'),
(1053, 'Vampiric Scepter', NULL, 'vampiric-scepter.png'),
(1054, 'Doran''s Shield', NULL, 'dorans-shield.png'),
(1055, 'Doran''s Blade', NULL, 'dorans-blade.png'),
(1056, 'Doran''s Ring', NULL, 'dorans-ring.png'),
(1057, 'Negatron Cloak', NULL, 'negatron-cloak.png'),
(1058, 'Needlessly Large Rod', NULL, 'needlessly-large-rod.png'),
(1082, 'Dark Seal', NULL, 'dark-seal.png'),
(1083, 'Cull', NULL, 'cull.png'),
(1086, 'Doran''s Bow', NULL, 'dorans-bow.png'),
(1090, 'Quest: Top', NULL, 'quest-top.png'),
(1091, 'Quest: Mid', NULL, 'quest-mid.png'),
(1092, 'Quest: Bot', NULL, 'quest-bot.png'),
(1093, 'Quest: Support', NULL, 'quest-support.png'),
(1094, 'Quest: Jungle', NULL, 'quest-jungle.png'),
(1101, 'Scorchclaw Pup', NULL, 'scorchclaw-pup.png'),
(1102, 'Gustwalker Hatchling', NULL, 'gustwalker-hatchling.png'),
(1103, 'Mosstomper Seedling', NULL, 'mosstomper-seedling.png'),
(1104, 'Eye of the Herald', NULL, 'eye-of-the-herald.png'),
(1105, 'Mosstomper Seedling', NULL, 'mosstomper-seedling.png'),
(1106, 'Gustwalker Hatchling', NULL, 'gustwalker-hatchling.png'),
(1107, 'Scorchclaw Pup', NULL, 'scorchclaw-pup.png'),
(1111, 'Jarvan I''s', NULL, 'jarvan-is.png'),
(1120, 'Doran''s Helm', NULL, 'dorans-helm.png'),
(1200, 'Top Lane Quest', NULL, 'top-lane-quest.png'),
(1201, 'Mid Lane Quest', NULL, 'mid-lane-quest.png'),
(1202, 'Bot Lane Quest', NULL, 'bot-lane-quest.png'),
(1203, 'Support Quest', NULL, 'support-quest.png'),
(1204, 'Jungle Quest', NULL, 'jungle-quest.png'),
(1205, 'Jungle Quest Reward', NULL, 'jungle-quest-reward.png'),
(1206, 'Mid Lane Quest Reward', NULL, 'mid-lane-quest-reward.png'),
(1207, 'Bot Lane Quest Reward', NULL, 'bot-lane-quest-reward.png'),
(1208, 'Support Quest Reward', NULL, 'support-quest-reward.png'),
(1209, 'Jungle Quest Reward', NULL, 'jungle-quest-reward.png'),
(1210, 'Jungle Quest Reward', NULL, 'jungle-quest-reward.png'),
(1211, 'Jungle Quest Reward', NULL, 'jungle-quest-reward.png'),
(1220, 'Unleashed Teleport (Top Lane Quest Reward)', NULL, 'unleashed-teleport-top-lane-quest-reward.png'),
(1221, 'Top Lane Quest Reward', NULL, 'top-lane-quest-reward.png'),
(1222, 'Top Lane Quest', NULL, 'top-lane-quest.png'),
(123430, 'Rite of Ruin', NULL, 'rite-of-ruin.png'),
(124011, 'Sword of Blossoming Dawn', NULL, 'sword-of-blossoming-dawn.png'),
(126697, 'Hubris', NULL, 'hubris.png'),
(1500, 'Penetrating Bullets', NULL, 'penetrating-bullets.png'),
(1501, 'Fortification', NULL, 'fortification.png'),
(1502, 'Reinforced Armor', NULL, 'reinforced-armor.png'),
(1503, 'Warden''s Eye', NULL, 'wardens-eye.png'),
(1504, 'Vanguard', NULL, 'vanguard.png'),
(1505, 'Reinforced Armor', NULL, 'reinforced-armor.png'),
(1506, 'Reinforced Armor', NULL, 'reinforced-armor.png'),
(1507, 'Overcharged', NULL, 'overcharged.png'),
(1508, 'Anti-tower Socks', NULL, 'antitower-socks.png'),
(1509, 'Gusto', NULL, 'gusto.png'),
(1510, 'Phreakish Gusto', NULL, 'phreakish-gusto.png'),
(1511, 'Super Mech Armor', NULL, 'super-mech-armor.png'),
(1512, 'Super Mech Power Field', NULL, 'super-mech-power-field.png'),
(1515, 'Turret Plating', NULL, 'turret-plating.png'),
(1516, 'Structure Bounty', NULL, 'structure-bounty.png'),
(1517, 'Structure Bounty', NULL, 'structure-bounty.png'),
(1518, 'Structure Bounty', NULL, 'structure-bounty.png'),
(1519, 'Structure Bounty', NULL, 'structure-bounty.png'),
(1520, 'OvererchargedHA', NULL, 'overerchargedha.png'),
(1521, 'Fortification', NULL, 'fortification.png'),
(1522, 'Tower Power-Up', NULL, 'tower-powerup.png'),
(1523, 'Overcharged', NULL, 'overcharged.png'),
(1524, 'Overgrowth', NULL, 'overgrowth.png'),
(2001, 'Recall', NULL, 'recall.png'),
(2002, 'Enhanced Recall', NULL, 'enhanced-recall.png'),
(2003, 'Health Potion', NULL, 'health-potion.png'),
(2007, 'Disabled Recall', NULL, 'disabled-recall.png'),
(2010, 'Total Biscuit of Everlasting Will', NULL, 'total-biscuit-of-everlasting-will.png'),
(2015, 'Kircheis Shard', NULL, 'kircheis-shard.png'),
(2019, 'Steel Sigil', NULL, 'steel-sigil.png'),
(2020, 'The Brutalizer', NULL, 'the-brutalizer.png'),
(2021, 'Tunneler', NULL, 'tunneler.png'),
(2022, 'Glowing Mote', NULL, 'glowing-mote.png'),
(2031, 'Refillable Potion', NULL, 'refillable-potion.png'),
(2033, 'Corrupting Potion', NULL, 'corrupting-potion.png'),
(2049, 'Guardian''s Amulet', NULL, 'guardians-amulet.png'),
(2050, 'Guardian''s Shroud', NULL, 'guardians-shroud.png'),
(2051, 'Guardian''s Horn', NULL, 'guardians-horn.png'),
(2052, 'Poro-Snax', NULL, 'porosnax.png'),
(2055, 'Control Ward', NULL, 'control-ward.png'),
(2056, 'Stealth Ward', NULL, 'stealth-ward.png'),
(2065, 'Shurelya''s Battlesong', NULL, 'shurelyas-battlesong.png'),
(2138, 'Elixir of Iron', NULL, 'elixir-of-iron.png'),
(2139, 'Elixir of Sorcery', NULL, 'elixir-of-sorcery.png'),
(2140, 'Elixir of Wrath', NULL, 'elixir-of-wrath.png'),
(2141, 'Cappa Juice', NULL, 'cappa-juice.png'),
(2142, 'Juice of Power', NULL, 'juice-of-power.png'),
(2143, 'Juice of Vitality', NULL, 'juice-of-vitality.png'),
(2144, 'Juice of Haste', NULL, 'juice-of-haste.png'),
(2145, 'Lucky Dice', NULL, 'lucky-dice.png'),
(2146, 'Enhanced Lucky Dice', NULL, 'enhanced-lucky-dice.png'),
(2147, 'Augment Level', NULL, 'augment-level.png'),
(2150, 'Elixir of Skill', NULL, 'elixir-of-skill.png'),
(2151, 'Elixir of Avarice', NULL, 'elixir-of-avarice.png'),
(2152, 'Elixir of Force', NULL, 'elixir-of-force.png'),
(2161, 'Bandle Juice of Power', NULL, 'bandle-juice-of-power.png'),
(2162, 'Bandle Juice of Vitality', NULL, 'bandle-juice-of-vitality.png'),
(2163, 'Bandle Juice of Haste', NULL, 'bandle-juice-of-haste.png'),
(220000, 'Stat Bonus', NULL, 'stat-bonus.png'),
(220001, 'Legendary Fighter Item', NULL, 'legendary-fighter-item.png'),
(220002, 'Legendary Marksman Item', NULL, 'legendary-marksman-item.png'),
(220003, 'Legendary Assassin Item', NULL, 'legendary-assassin-item.png'),
(220004, 'Legendary Mage Item', NULL, 'legendary-mage-item.png'),
(220005, 'Legendary Tank Item', NULL, 'legendary-tank-item.png'),
(220006, 'Legendary Support Item', NULL, 'legendary-support-item.png'),
(220007, 'Prismatic Item', NULL, 'prismatic-item.png'),
(220008, 'Anvil Voucher', NULL, 'anvil-voucher.png'),
(220009, 'Gold Stat Anvil Voucher', NULL, 'gold-stat-anvil-voucher.png'),
(220010, 'Prismatic Stat Voucher', NULL, 'prismatic-stat-voucher.png'),
(220011, 'Bravery Voucher', NULL, 'bravery-voucher.png'),
(220012, 'Shardblade', NULL, 'shardblade.png'),
(221011, 'Giant''s Belt', NULL, 'giants-belt.png'),
(221026, 'Blasting Wand', NULL, 'blasting-wand.png'),
(221031, 'Chain Vest', NULL, 'chain-vest.png'),
(221038, 'B. F. Sword', NULL, 'b-f-sword.png'),
(221043, 'Recurve Bow', NULL, 'recurve-bow.png'),
(221053, 'Vampiric Scepter', NULL, 'vampiric-scepter.png'),
(221057, 'Negatron Cloak', NULL, 'negatron-cloak.png'),
(221058, 'Needlessly Large Rod', NULL, 'needlessly-large-rod.png'),
(222022, 'Glowing Mote', NULL, 'glowing-mote.png'),
(222051, 'Guardian''s Horn', NULL, 'guardians-horn.png'),
(222065, 'Shurelya''s Battlesong', NULL, 'shurelyas-battlesong.png'),
(222141, 'Cappa Juice', NULL, 'cappa-juice.png'),
(222502, 'Unending Despair', NULL, 'unending-despair.png'),
(222503, 'Blackfire Torch', NULL, 'blackfire-torch.png'),
(222504, 'Kaenic Rookern', NULL, 'kaenic-rookern.png'),
(222510, 'Dusk and Dawn', NULL, 'dusk-and-dawn.png'),
(222512, 'Fiendhunter Bolts', NULL, 'fiendhunter-bolts.png'),
(222517, 'Endless Hunger', NULL, 'endless-hunger.png'),
(222522, 'Actualizer', NULL, 'actualizer.png'),
(222523, 'Hexoptics C44', NULL, 'hexoptics-c44.png'),
(222524, 'Bandlepipes', NULL, 'bandlepipes.png'),
(222525, 'Protoplasm Harness', NULL, 'protoplasm-harness.png'),
(222526, 'Whispering Circlet', NULL, 'whispering-circlet.png'),
(222530, 'Diadem of Songs', NULL, 'diadem-of-songs.png'),
(223001, 'Evenshroud', NULL, 'evenshroud.png'),
(223002, 'Trailblazer', NULL, 'trailblazer.png'),
(223003, 'Archangel''s Staff', NULL, 'archangels-staff.png'),
(223004, 'Manamune', NULL, 'manamune.png'),
(223005, 'Ghostcrawlers', NULL, 'ghostcrawlers.png'),
(223006, 'Berserker''s Greaves', NULL, 'berserkers-greaves.png'),
(223008, 'Gluttonous Greaves', NULL, 'gluttonous-greaves.png'),
(223009, 'Boots of Swiftness', NULL, 'boots-of-swiftness.png'),
(223011, 'Chemtech Putrifier', NULL, 'chemtech-putrifier.png'),
(223020, 'Sorcerer''s Shoes', NULL, 'sorcerers-shoes.png'),
(223026, 'Guardian Angel', NULL, 'guardian-angel.png'),
(223031, 'Infinity Edge', NULL, 'infinity-edge.png'),
(223032, 'Yun Tal Wildarrows', NULL, 'yun-tal-wildarrows.png'),
(223033, 'Mortal Reminder', NULL, 'mortal-reminder.png'),
(223036, 'Lord Dominik''s Regards', NULL, 'lord-dominiks-regards.png'),
(223039, 'Atma''s Reckoning', NULL, 'atmas-reckoning.png'),
(223040, 'Seraph''s Embrace', NULL, 'seraphs-embrace.png'),
(223042, 'Muramana', NULL, 'muramana.png'),
(223046, 'Phantom Dancer', NULL, 'phantom-dancer.png'),
(223047, 'Plated Steelcaps', NULL, 'plated-steelcaps.png'),
(223050, 'Zeke''s Convergence', NULL, 'zekes-convergence.png'),
(223053, 'Sterak''s Gage', NULL, 'steraks-gage.png'),
(223057, 'Sheen', NULL, 'sheen.png'),
(223065, 'Spirit Visage', NULL, 'spirit-visage.png'),
(223067, 'Kindlegem', NULL, 'kindlegem.png'),
(223068, 'Sunfire Aegis', NULL, 'sunfire-aegis.png'),
(223069, 'Void Immolation', NULL, 'void-immolation.png'),
(223071, 'Black Cleaver', NULL, 'black-cleaver.png'),
(223072, 'Bloodthirster', NULL, 'bloodthirster.png'),
(223073, 'Experimental Hexplate', NULL, 'experimental-hexplate.png'),
(223074, 'Ravenous Hydra', NULL, 'ravenous-hydra.png'),
(223075, 'Thornmail', NULL, 'thornmail.png'),
(223078, 'Trinity Force', NULL, 'trinity-force.png'),
(223084, 'Heartsteel', NULL, 'heartsteel.png'),
(223085, 'Runaan''s Hurricane', NULL, 'runaans-hurricane.png'),
(223087, 'Statikk Shiv', NULL, 'statikk-shiv.png'),
(223089, 'Rabadon''s Deathcap', NULL, 'rabadons-deathcap.png'),
(223091, 'Wit''s End', NULL, 'wits-end.png'),
(223094, 'Rapid Firecannon', NULL, 'rapid-firecannon.png'),
(223095, 'Stormrazor', NULL, 'stormrazor.png'),
(223100, 'Lich Bane', NULL, 'lich-bane.png'),
(223102, 'Banshee''s Veil', NULL, 'banshees-veil.png'),
(223105, 'Aegis of the Legion', NULL, 'aegis-of-the-legion.png'),
(223107, 'Redemption', NULL, 'redemption.png'),
(223109, 'Knight''s Vow', NULL, 'knights-vow.png'),
(223110, 'Frozen Heart', NULL, 'frozen-heart.png'),
(223111, 'Mercury''s Treads', NULL, 'mercurys-treads.png'),
(223112, 'Guardian''s Orb', NULL, 'guardians-orb.png'),
(223115, 'Nashor''s Tooth', NULL, 'nashors-tooth.png'),
(223116, 'Rylai''s Crystal Scepter', NULL, 'rylais-crystal-scepter.png'),
(223118, 'Malignance', NULL, 'malignance.png'),
(223119, 'Winter''s Approach', NULL, 'winters-approach.png'),
(223121, 'Fimbulwinter', NULL, 'fimbulwinter.png'),
(223124, 'Guinsoo''s Rageblade', NULL, 'guinsoos-rageblade.png'),
(223135, 'Void Staff', NULL, 'void-staff.png'),
(223137, 'Cryptbloom', NULL, 'cryptbloom.png'),
(223139, 'Mercurial Scimitar', NULL, 'mercurial-scimitar.png'),
(223142, 'Youmuu''s Ghostblade', NULL, 'youmuus-ghostblade.png'),
(223143, 'Randuin''s Omen', NULL, 'randuins-omen.png'),
(223146, 'Hextech Gunblade', NULL, 'hextech-gunblade.png'),
(223152, 'Hextech Rocketbelt', NULL, 'hextech-rocketbelt.png'),
(223153, 'Blade of The Ruined King', NULL, 'blade-of-the-ruined-king.png'),
(223156, 'Maw of Malmortius', NULL, 'maw-of-malmortius.png'),
(223157, 'Zhonya''s Hourglass', NULL, 'zhonyas-hourglass.png'),
(223158, 'Ionian Boots of Lucidity', NULL, 'ionian-boots-of-lucidity.png'),
(223161, 'Spear of Shojin', NULL, 'spear-of-shojin.png'),
(223165, 'Morellonomicon', NULL, 'morellonomicon.png'),
(223172, 'Zephyr', NULL, 'zephyr.png'),
(223177, 'Guardian''s Blade', NULL, 'guardians-blade.png'),
(223181, 'Hullbreaker', NULL, 'hullbreaker.png'),
(223184, 'Guardian''s Hammer', NULL, 'guardians-hammer.png'),
(223185, 'Guardian''s Dirk', NULL, 'guardians-dirk.png'),
(223190, 'Locket of the Iron Solari', NULL, 'locket-of-the-iron-solari.png'),
(223193, 'Gargoyle Stoneplate', NULL, 'gargoyle-stoneplate.png'),
(223222, 'Mikael''s Blessing', NULL, 'mikaels-blessing.png'),
(223302, 'Terminus', NULL, 'terminus.png'),
(223504, 'Ardent Censer', NULL, 'ardent-censer.png'),
(223508, 'Essence Reaver', NULL, 'essence-reaver.png'),
(223742, 'Dead Man''s Plate', NULL, 'dead-mans-plate.png'),
(223748, 'Titanic Hydra', NULL, 'titanic-hydra.png'),
(223814, 'Edge of Night', NULL, 'edge-of-night.png'),
(224004, 'Spectral Cutlass', NULL, 'spectral-cutlass.png'),
(224005, 'Imperial Mandate', NULL, 'imperial-mandate.png'),
(224401, 'Force of Nature', NULL, 'force-of-nature.png'),
(224403, 'The Golden Spatula', NULL, 'the-golden-spatula.png'),
(224628, 'Horizon Focus', NULL, 'horizon-focus.png'),
(224629, 'Cosmic Drive', NULL, 'cosmic-drive.png'),
(224633, 'Riftmaker', NULL, 'riftmaker.png'),
(224636, 'Night Harvester', NULL, 'night-harvester.png'),
(224637, 'Demonic Embrace', NULL, 'demonic-embrace.png'),
(224644, 'Crown of the Shattered Queen', NULL, 'crown-of-the-shattered-queen.png'),
(224645, 'Shadowflame', NULL, 'shadowflame.png'),
(224646, 'Stormsurge', NULL, 'stormsurge.png'),
(226035, 'Silvermere Dawn', NULL, 'silvermere-dawn.png'),
(226333, 'Death''s Dance', NULL, 'deaths-dance.png'),
(226609, 'Chempunk Chainsword', NULL, 'chempunk-chainsword.png'),
(226610, 'Sundered Sky', NULL, 'sundered-sky.png'),
(226616, 'Staff of Flowing Water', NULL, 'staff-of-flowing-water.png'),
(226617, 'Moonstone Renewer', NULL, 'moonstone-renewer.png'),
(226620, 'Echoes of Helia', NULL, 'echoes-of-helia.png'),
(226621, 'Dawncore', NULL, 'dawncore.png'),
(226630, 'Goredrinker', NULL, 'goredrinker.png'),
(226631, 'Stridebreaker', NULL, 'stridebreaker.png'),
(226632, 'Divine Sunderer', NULL, 'divine-sunderer.png'),
(226653, 'Liandry''s Anguish', NULL, 'liandrys-anguish.png'),
(226655, 'Luden''s Echo', NULL, 'ludens-echo.png'),
(226656, 'Everfrost', NULL, 'everfrost.png'),
(226657, 'Rod of Ages', NULL, 'rod-of-ages.png'),
(226662, 'Iceborn Gauntlet', NULL, 'iceborn-gauntlet.png'),
(226664, 'Hollow Radiance', NULL, 'hollow-radiance.png'),
(226665, 'Jak''Sho, The Protean', NULL, 'jaksho-the-protean.png'),
(226667, 'Radiant Virtue', NULL, 'radiant-virtue.png'),
(226671, 'Galeforce', NULL, 'galeforce.png'),
(226672, 'Kraken Slayer', NULL, 'kraken-slayer.png'),
(226673, 'Immortal Shieldbow', NULL, 'immortal-shieldbow.png'),
(226675, 'Navori Flickerblades', NULL, 'navori-flickerblades.png'),
(226676, 'The Collector', NULL, 'the-collector.png'),
(226691, 'Duskblade of Draktharr', NULL, 'duskblade-of-draktharr.png'),
(226692, 'Eclipse', NULL, 'eclipse.png'),
(226693, 'Prowler''s Claw', NULL, 'prowlers-claw.png'),
(226694, 'Serylda''s Grudge', NULL, 'seryldas-grudge.png'),
(226695, 'Serpent''s Fang', NULL, 'serpents-fang.png'),
(226696, 'Axiom Arc', NULL, 'axiom-arc.png'),
(226697, 'Hubris', NULL, 'hubris.png'),
(226698, 'Profane Hydra', NULL, 'profane-hydra.png'),
(226699, 'Voltaic Cyclosword', NULL, 'voltaic-cyclosword.png'),
(226701, 'Opportunity', NULL, 'opportunity.png'),
(228001, 'Anathema''s Chains', NULL, 'anathemas-chains.png'),
(228002, 'Wooglet''s Witchcap', NULL, 'wooglets-witchcap.png'),
(228003, 'Deathblade', NULL, 'deathblade.png'),
(228004, 'Adaptive Helm', NULL, 'adaptive-helm.png'),
(228005, 'Obsidian Cleaver', NULL, 'obsidian-cleaver.png'),
(228006, 'Sanguine Blade', NULL, 'sanguine-blade.png'),
(228008, 'Runeglaive', NULL, 'runeglaive.png'),
(228009, 'Multitool', NULL, 'multitool.png'),
(228020, 'Abyssal Mask', NULL, 'abyssal-mask.png'),
(2403, 'Minion Dematerializer', NULL, 'minion-dematerializer.png'),
(2420, 'Seeker''s Armguard', NULL, 'seekers-armguard.png'),
(2421, 'Shattered Armguard', NULL, 'shattered-armguard.png'),
(2422, 'Slightly Magical Footwear', NULL, 'slightly-magical-footwear.png'),
(2501, 'Overlord''s Bloodmail', NULL, 'overlords-bloodmail.png'),
(2502, 'Unending Despair', NULL, 'unending-despair.png'),
(2503, 'Blackfire Torch', NULL, 'blackfire-torch.png'),
(2504, 'Kaenic Rookern', NULL, 'kaenic-rookern.png'),
(2508, 'Fated Ashes', NULL, 'fated-ashes.png'),
(2510, 'Dusk and Dawn', NULL, 'dusk-and-dawn.png'),
(2512, 'Fiendhunter Bolts', NULL, 'fiendhunter-bolts.png'),
(2517, 'Endless Hunger', NULL, 'endless-hunger.png'),
(2520, 'Bastionbreaker', NULL, 'bastionbreaker.png'),
(2522, 'Actualizer', NULL, 'actualizer.png'),
(2523, 'Hexoptics C44', NULL, 'hexoptics-c44.png'),
(2524, 'Bandlepipes', NULL, 'bandlepipes.png'),
(2525, 'Protoplasm Harness', NULL, 'protoplasm-harness.png'),
(2526, 'Whispering Circlet', NULL, 'whispering-circlet.png'),
(2530, 'Diadem of Songs', NULL, 'diadem-of-songs.png'),
(3001, 'Evenshroud', NULL, 'evenshroud.png'),
(3002, 'Trailblazer', NULL, 'trailblazer.png'),
(3003, 'Archangel''s Staff', NULL, 'archangels-staff.png'),
(3004, 'Manamune', NULL, 'manamune.png'),
(3005, 'Ghostcrawlers', NULL, 'ghostcrawlers.png'),
(3006, 'Berserker''s Greaves', NULL, 'berserkers-greaves.png'),
(3008, 'Gluttonous Greaves', NULL, 'gluttonous-greaves.png'),
(3009, 'Boots of Swiftness', NULL, 'boots-of-swiftness.png'),
(3010, 'Symbiotic Soles', NULL, 'symbiotic-soles.png'),
(3011, 'Chemtech Putrifier', NULL, 'chemtech-putrifier.png'),
(3012, 'Chalice of Blessing', NULL, 'chalice-of-blessing.png'),
(3013, 'Synchronized Souls', NULL, 'synchronized-souls.png'),
(3020, 'Sorcerer''s Shoes', NULL, 'sorcerers-shoes.png'),
(3023, 'Lifewell Pendant', NULL, 'lifewell-pendant.png'),
(3024, 'Glacial Buckler', NULL, 'glacial-buckler.png'),
(3026, 'Guardian Angel', NULL, 'guardian-angel.png'),
(3031, 'Infinity Edge', NULL, 'infinity-edge.png'),
(3032, 'Yun Tal Wildarrows', NULL, 'yun-tal-wildarrows.png'),
(3033, 'Mortal Reminder', NULL, 'mortal-reminder.png'),
(3035, 'Last Whisper', NULL, 'last-whisper.png'),
(3036, 'Lord Dominik''s Regards', NULL, 'lord-dominiks-regards.png'),
(3039, 'Atma''s Reckoning', NULL, 'atmas-reckoning.png'),
(3040, 'Seraph''s Embrace', NULL, 'seraphs-embrace.png'),
(3041, 'Mejai''s Soulstealer', NULL, 'mejais-soulstealer.png'),
(3042, 'Muramana', NULL, 'muramana.png'),
(3044, 'Phage', NULL, 'phage.png'),
(3046, 'Phantom Dancer', NULL, 'phantom-dancer.png'),
(3047, 'Plated Steelcaps', NULL, 'plated-steelcaps.png'),
(3050, 'Zeke''s Convergence', NULL, 'zekes-convergence.png'),
(3051, 'Hearthbound Axe', NULL, 'hearthbound-axe.png'),
(3053, 'Sterak''s Gage', NULL, 'steraks-gage.png'),
(3057, 'Sheen', NULL, 'sheen.png'),
(3065, 'Spirit Visage', NULL, 'spirit-visage.png'),
(3066, 'Winged Moonplate', NULL, 'winged-moonplate.png'),
(3067, 'Kindlegem', NULL, 'kindlegem.png'),
(3068, 'Sunfire Aegis', NULL, 'sunfire-aegis.png'),
(3070, 'Tear of the Goddess', NULL, 'tear-of-the-goddess.png'),
(3071, 'Black Cleaver', NULL, 'black-cleaver.png'),
(3072, 'Bloodthirster', NULL, 'bloodthirster.png'),
(3073, 'Experimental Hexplate', NULL, 'experimental-hexplate.png'),
(3074, 'Ravenous Hydra', NULL, 'ravenous-hydra.png'),
(3075, 'Thornmail', NULL, 'thornmail.png'),
(3076, 'Bramble Vest', NULL, 'bramble-vest.png'),
(3077, 'Tiamat', NULL, 'tiamat.png'),
(3078, 'Trinity Force', NULL, 'trinity-force.png'),
(3082, 'Warden''s Mail', NULL, 'wardens-mail.png'),
(3083, 'Warmog''s Armor', NULL, 'warmogs-armor.png'),
(3084, 'Heartsteel', NULL, 'heartsteel.png'),
(3085, 'Runaan''s Hurricane', NULL, 'runaans-hurricane.png'),
(3086, 'Zeal', NULL, 'zeal.png'),
(3087, 'Statikk Shiv', NULL, 'statikk-shiv.png'),
(3089, 'Rabadon''s Deathcap', NULL, 'rabadons-deathcap.png'),
(3091, 'Wit''s End', NULL, 'wits-end.png'),
(3094, 'Rapid Firecannon', NULL, 'rapid-firecannon.png'),
(3095, 'Deprecated item', NULL, 'deprecated-item.png'),
(3097, 'Stormrazor', NULL, 'stormrazor.png'),
(3100, 'Lich Bane', NULL, 'lich-bane.png'),
(3102, 'Banshee''s Veil', NULL, 'banshees-veil.png'),
(3105, 'Aegis of the Legion', NULL, 'aegis-of-the-legion.png'),
(3107, 'Redemption', NULL, 'redemption.png'),
(3108, 'Fiendish Codex', NULL, 'fiendish-codex.png'),
(3109, 'Knight''s Vow', NULL, 'knights-vow.png'),
(3110, 'Frozen Heart', NULL, 'frozen-heart.png'),
(3111, 'Mercury''s Treads', NULL, 'mercurys-treads.png'),
(3112, 'Guardian''s Orb', NULL, 'guardians-orb.png'),
(3113, 'Aether Wisp', NULL, 'aether-wisp.png'),
(3114, 'Forbidden Idol', NULL, 'forbidden-idol.png'),
(3115, 'Nashor''s Tooth', NULL, 'nashors-tooth.png'),
(3116, 'Rylai''s Crystal Scepter', NULL, 'rylais-crystal-scepter.png'),
(3117, 'Mobility Boots', NULL, 'mobility-boots.png'),
(3118, 'Malignance', NULL, 'malignance.png'),
(3119, 'Winter''s Approach', NULL, 'winters-approach.png'),
(3121, 'Fimbulwinter', NULL, 'fimbulwinter.png'),
(3123, 'Executioner''s Calling', NULL, 'executioners-calling.png'),
(3124, 'Guinsoo''s Rageblade', NULL, 'guinsoos-rageblade.png'),
(3128, 'Deathfire Grasp', NULL, 'deathfire-grasp.png'),
(3131, 'Sword of the Divine', NULL, 'sword-of-the-divine.png'),
(3133, 'Caulfield''s Warhammer', NULL, 'caulfields-warhammer.png'),
(3134, 'Serrated Dirk', NULL, 'serrated-dirk.png'),
(3135, 'Void Staff', NULL, 'void-staff.png'),
(3137, 'Cryptbloom', NULL, 'cryptbloom.png'),
(3139, 'Mercurial Scimitar', NULL, 'mercurial-scimitar.png'),
(3140, 'Quicksilver Sash', NULL, 'quicksilver-sash.png'),
(3142, 'Youmuu''s Ghostblade', NULL, 'youmuus-ghostblade.png'),
(3143, 'Randuin''s Omen', NULL, 'randuins-omen.png'),
(3144, 'Scout''s Slingshot', NULL, 'scouts-slingshot.png'),
(3145, 'Hextech Alternator', NULL, 'hextech-alternator.png'),
(3146, 'Hextech Gunblade', NULL, 'hextech-gunblade.png'),
(3147, 'Haunting Guise', NULL, 'haunting-guise.png'),
(3152, 'Hextech Rocketbelt', NULL, 'hextech-rocketbelt.png'),
(3153, 'Blade of The Ruined King', NULL, 'blade-of-the-ruined-king.png'),
(3155, 'Hexdrinker', NULL, 'hexdrinker.png'),
(3156, 'Maw of Malmortius', NULL, 'maw-of-malmortius.png'),
(3157, 'Zhonya''s Hourglass', NULL, 'zhonyas-hourglass.png'),
(3158, 'Ionian Boots of Lucidity', NULL, 'ionian-boots-of-lucidity.png'),
(3161, 'Spear of Shojin', NULL, 'spear-of-shojin.png'),
(3165, 'Morellonomicon', NULL, 'morellonomicon.png'),
(3168, 'Immortal Path', NULL, 'immortal-path.png'),
(3170, 'Swiftmarch', NULL, 'swiftmarch.png'),
(3171, 'Crimson Lucidity', NULL, 'crimson-lucidity.png'),
(3172, 'Gunmetal Greaves', NULL, 'gunmetal-greaves.png'),
(3173, 'Chainlaced Crushers', NULL, 'chainlaced-crushers.png'),
(3174, 'Armored Advance', NULL, 'armored-advance.png'),
(3175, 'Spellslinger''s Shoes', NULL, 'spellslingers-shoes.png'),
(3176, 'Forever Forward', NULL, 'forever-forward.png'),
(3177, 'Guardian''s Blade', NULL, 'guardians-blade.png'),
(3179, 'Umbral Glaive', NULL, 'umbral-glaive.png'),
(3181, 'Hullbreaker', NULL, 'hullbreaker.png'),
(3184, 'Guardian''s Hammer', NULL, 'guardians-hammer.png'),
(3190, 'Locket of the Iron Solari', NULL, 'locket-of-the-iron-solari.png'),
(3193, 'Gargoyle Stoneplate', NULL, 'gargoyle-stoneplate.png'),
(3211, 'Spectre''s Cowl', NULL, 'spectres-cowl.png'),
(322065, 'Shurelya''s Battlesong', NULL, 'shurelyas-battlesong.png'),
(3222, 'Mikael''s Blessing', NULL, 'mikaels-blessing.png'),
(322526, 'Whispering Circlet', NULL, 'whispering-circlet.png'),
(322530, 'Diadem of Songs', NULL, 'diadem-of-songs.png'),
(323002, 'Trailblazer', NULL, 'trailblazer.png'),
(323003, 'Archangel''s Staff', NULL, 'archangels-staff.png'),
(323004, 'Manamune', NULL, 'manamune.png'),
(323040, 'Seraph''s Embrace', NULL, 'seraphs-embrace.png'),
(323042, 'Muramana', NULL, 'muramana.png'),
(323050, 'Zeke''s Convergence', NULL, 'zekes-convergence.png'),
(323070, 'Tear of the Goddess', NULL, 'tear-of-the-goddess.png'),
(323075, 'Thornmail', NULL, 'thornmail.png'),
(323107, 'Redemption', NULL, 'redemption.png'),
(323109, 'Knight''s Vow', NULL, 'knights-vow.png'),
(323110, 'Frozen Heart', NULL, 'frozen-heart.png'),
(323119, 'Winter''s Approach', NULL, 'winters-approach.png'),
(323121, 'Fimbulwinter', NULL, 'fimbulwinter.png'),
(323190, 'Locket of the Iron Solari', NULL, 'locket-of-the-iron-solari.png'),
(323222, 'Mikael''s Blessing', NULL, 'mikaels-blessing.png'),
(323504, 'Ardent Censer', NULL, 'ardent-censer.png'),
(324005, 'Imperial Mandate', NULL, 'imperial-mandate.png'),
(326616, 'Staff of Flowing Water', NULL, 'staff-of-flowing-water.png'),
(326617, 'Moonstone Renewer', NULL, 'moonstone-renewer.png'),
(326620, 'Echoes of Helia', NULL, 'echoes-of-helia.png'),
(326621, 'Dawncore', NULL, 'dawncore.png'),
(326657, 'Rod of Ages', NULL, 'rod-of-ages.png'),
(328020, 'Abyssal Mask', NULL, 'abyssal-mask.png'),
(3302, 'Terminus', NULL, 'terminus.png'),
(3330, 'Scarecrow Effigy', NULL, 'scarecrow-effigy.png'),
(3340, 'Stealth Ward', NULL, 'stealth-ward.png'),
(3348, 'Arcane Sweeper', NULL, 'arcane-sweeper.png'),
(3349, 'Lucent Singularity', NULL, 'lucent-singularity.png'),
(3363, 'Farsight Alteration', NULL, 'farsight-alteration.png'),
(3364, 'Oracle Lens', NULL, 'oracle-lens.png'),
(3398, 'Small Party Favor', NULL, 'small-party-favor.png'),
(3399, 'Party Favor', NULL, 'party-favor.png'),
(3400, 'Your Cut', NULL, 'your-cut.png'),
(3430, 'Rite Of Ruin', NULL, 'rite-of-ruin.png'),
(3504, 'Ardent Censer', NULL, 'ardent-censer.png'),
(3508, 'Essence Reaver', NULL, 'essence-reaver.png'),
(3513, 'Eye of the Herald', NULL, 'eye-of-the-herald.png'),
(3599, 'Kalista''s Black Spear', NULL, 'kalistas-black-spear.png'),
(3600, 'Kalista''s Black Spear', NULL, 'kalistas-black-spear.png'),
(3742, 'Dead Man''s Plate', NULL, 'dead-mans-plate.png'),
(3748, 'Titanic Hydra', NULL, 'titanic-hydra.png'),
(3801, 'Crystalline Bracer', NULL, 'crystalline-bracer.png'),
(3802, 'Lost Chapter', NULL, 'lost-chapter.png'),
(3803, 'Catalyst of Aeons', NULL, 'catalyst-of-aeons.png'),
(3814, 'Edge of Night', NULL, 'edge-of-night.png'),
(3850, 'Spellthief''s Edge', NULL, 'spellthiefs-edge.png'),
(3851, 'Frostfang', NULL, 'frostfang.png'),
(3853, 'Shard of True Ice', NULL, 'shard-of-true-ice.png'),
(3854, 'Steel Shoulderguards', NULL, 'steel-shoulderguards.png'),
(3855, 'Runesteel Spaulders', NULL, 'runesteel-spaulders.png'),
(3857, 'Pauldrons of Whiterock', NULL, 'pauldrons-of-whiterock.png'),
(3858, 'Relic Shield', NULL, 'relic-shield.png'),
(3859, 'Targon''s Buckler', NULL, 'targons-buckler.png'),
(3860, 'Bulwark of the Mountain', NULL, 'bulwark-of-the-mountain.png'),
(3862, 'Spectral Sickle', NULL, 'spectral-sickle.png'),
(3863, 'Harrowing Crescent', NULL, 'harrowing-crescent.png'),
(3864, 'Black Mist Scythe', NULL, 'black-mist-scythe.png'),
(3865, 'World Atlas', NULL, 'world-atlas.png'),
(3866, 'Runic Compass', NULL, 'runic-compass.png'),
(3867, 'Bounty of Worlds', NULL, 'bounty-of-worlds.png'),
(3869, 'Celestial Opposition', NULL, 'celestial-opposition.png'),
(3870, 'Dream Maker', NULL, 'dream-maker.png'),
(3871, 'Zaz''Zak''s Realmspike', NULL, 'zazzaks-realmspike.png'),
(3876, 'Solstice Sleigh', NULL, 'solstice-sleigh.png'),
(3877, 'Bloodsong', NULL, 'bloodsong.png'),
(3901, '<rarityLegendary>Fire at Will</rarityLegendary><br><subtitleLeft><silver>500 Silver Serpents</silver></subtitleLeft>', NULL, 'raritylegendaryfire-at-willraritylegendarybrsubtitleleftsilver500-silver-serpentssilversubtitleleft.png'),
(3902, '<rarityLegendary>Death''s Daughter</rarityLegendary><br><subtitleLeft><silver>500 Silver Serpents</silver></subtitleLeft>', NULL, 'raritylegendarydeaths-daughterraritylegendarybrsubtitleleftsilver500-silver-serpentssilversubtitleleft.png'),
(3903, '<rarityLegendary>Raise Morale</rarityLegendary><br><subtitleLeft><silver>500 Silver Serpents</silver></subtitleLeft>', NULL, 'raritylegendaryraise-moraleraritylegendarybrsubtitleleftsilver500-silver-serpentssilversubtitleleft.png'),
(3916, 'Oblivion Orb', NULL, 'oblivion-orb.png'),
(4003, 'Lifeline', NULL, 'lifeline.png'),
(4004, 'Spectral Cutlass', NULL, 'spectral-cutlass.png'),
(4005, 'Imperial Mandate', NULL, 'imperial-mandate.png'),
(4010, 'Bloodletter''s Curse', NULL, 'bloodletters-curse.png'),
(4011, 'Sword of Blossoming Dawn', NULL, 'sword-of-blossoming-dawn.png'),
(4012, 'Sin Eater', NULL, 'sin-eater.png'),
(4013, 'Lightning Braid', NULL, 'lightning-braid.png'),
(4014, 'Frozen Mallet', NULL, 'frozen-mallet.png'),
(4015, 'Perplexity', NULL, 'perplexity.png'),
(4016, 'Wordless Promise', NULL, 'wordless-promise.png'),
(4017, 'Hellfire Hatchet', NULL, 'hellfire-hatchet.png'),
(4401, 'Force of Nature', NULL, 'force-of-nature.png'),
(4402, 'Innervating Locket', NULL, 'innervating-locket.png'),
(4403, 'The Golden Spatula', NULL, 'the-golden-spatula.png'),
(443054, 'Darksteel Talons', NULL, 'darksteel-talons.png'),
(443055, 'Fulmination', NULL, 'fulmination.png'),
(443056, 'Demon King''s Crown', NULL, 'demon-kings-crown.png'),
(443058, 'Shield of Molten Stone', NULL, 'shield-of-molten-stone.png'),
(443059, 'Cloak of Starry Night', NULL, 'cloak-of-starry-night.png'),
(443060, 'Sword of the Divine', NULL, 'sword-of-the-divine.png'),
(443061, 'Force Of Entropy', NULL, 'force-of-entropy.png'),
(443062, 'Sanguine Gift', NULL, 'sanguine-gift.png'),
(443063, 'Eleisa''s Miracle', NULL, 'eleisas-miracle.png'),
(443064, 'Talisman Of Ascension', NULL, 'talisman-of-ascension.png'),
(443069, 'Hamstringer', NULL, 'hamstringer.png'),
(443079, 'Turbo Chemtank', NULL, 'turbo-chemtank.png'),
(443080, 'Twin Mask', NULL, 'twin-mask.png'),
(443081, 'Hexbolt Companion', NULL, 'hexbolt-companion.png'),
(443083, 'Warmog''s Armor', NULL, 'warmogs-armor.png'),
(443090, 'Reaper''s Toll', NULL, 'reapers-toll.png'),
(443193, 'Gargoyle Stoneplate', NULL, 'gargoyle-stoneplate.png'),
(444636, 'Night Harvester', NULL, 'night-harvester.png'),
(444637, 'Demonic Embrace', NULL, 'demonic-embrace.png'),
(444644, 'Crown of the Shattered Queen', NULL, 'crown-of-the-shattered-queen.png'),
(446632, 'Divine Sunderer', NULL, 'divine-sunderer.png'),
(446656, 'Everfrost', NULL, 'everfrost.png'),
(446667, 'Radiant Virtue', NULL, 'radiant-virtue.png'),
(446671, 'Galeforce', NULL, 'galeforce.png'),
(446691, 'Duskblade of Draktharr', NULL, 'duskblade-of-draktharr.png'),
(446693, 'Prowler''s Claw', NULL, 'prowlers-claw.png'),
(447100, 'Mirage Blade', NULL, 'mirage-blade.png'),
(447101, 'Gambler''s Blade', NULL, 'gamblers-blade.png'),
(447102, 'Reality Fracture', NULL, 'reality-fracture.png'),
(447103, 'Hemomancer''s Helm', NULL, 'hemomancers-helm.png'),
(447104, 'Innervating Locket', NULL, 'innervating-locket.png'),
(447105, 'Empyrean Promise', NULL, 'empyrean-promise.png'),
(447106, 'Dragonheart', NULL, 'dragonheart.png'),
(447107, 'Decapitator', NULL, 'decapitator.png'),
(447108, 'Runecarver', NULL, 'runecarver.png'),
(447109, 'Cruelty', NULL, 'cruelty.png'),
(447110, 'Moonflair Spellblade', NULL, 'moonflair-spellblade.png'),
(447111, 'Overlord''s Bloodmail', NULL, 'overlords-bloodmail.png'),
(447112, 'Flesheater', NULL, 'flesheater.png'),
(447113, 'Detonation Orb', NULL, 'detonation-orb.png'),
(447114, 'Reverberation', NULL, 'reverberation.png'),
(447115, 'Regicide', NULL, 'regicide.png'),
(447116, 'Kinkou Jitte', NULL, 'kinkou-jitte.png'),
(447118, 'Pyromancer''s Cloak', NULL, 'pyromancers-cloak.png'),
(447119, 'Lightning Rod', NULL, 'lightning-rod.png'),
(447120, 'Diamond-Tipped Spear', NULL, 'diamondtipped-spear.png'),
(447121, 'Twilight''s Edge', NULL, 'twilights-edge.png'),
(447122, 'Black Hole Gauntlet', NULL, 'black-hole-gauntlet.png'),
(447123, 'Puppeteer', NULL, 'puppeteer.png'),
(4628, 'Horizon Focus', NULL, 'horizon-focus.png'),
(4629, 'Cosmic Drive', NULL, 'cosmic-drive.png'),
(4630, 'Blighting Jewel', NULL, 'blighting-jewel.png'),
(4632, 'Verdant Barrier', NULL, 'verdant-barrier.png'),
(4633, 'Riftmaker', NULL, 'riftmaker.png'),
(4635, 'Leeching Leer', NULL, 'leeching-leer.png'),
(4636, 'Night Harvester', NULL, 'night-harvester.png'),
(4637, 'Demonic Embrace', NULL, 'demonic-embrace.png'),
(4638, 'Watchful Wardstone', NULL, 'watchful-wardstone.png'),
(4641, 'Stirring Wardstone', NULL, 'stirring-wardstone.png'),
(4642, 'Bandleglass Mirror', NULL, 'bandleglass-mirror.png'),
(4643, 'Vigilant Wardstone', NULL, 'vigilant-wardstone.png'),
(4644, 'Crown of the Shattered Queen', NULL, 'crown-of-the-shattered-queen.png'),
(4645, 'Shadowflame', NULL, 'shadowflame.png'),
(4646, 'Stormsurge', NULL, 'stormsurge.png'),
(550001, 'Healthbar Splash: Blue', NULL, 'healthbar-splash-blue.png'),
(550002, 'Healthbar Splash: Orange', NULL, 'healthbar-splash-orange.png'),
(550003, 'Healthbar Splash: Green', NULL, 'healthbar-splash-green.png'),
(550004, 'Healthbar Splash: Pink', NULL, 'healthbar-splash-pink.png'),
(550005, 'Healthbar Cleanup: Reset Color', NULL, 'healthbar-cleanup-reset-color.png'),
(550006, 'Healthbar Splash: Rainbow', NULL, 'healthbar-splash-rainbow.png'),
(550007, 'Party Favor', NULL, 'party-favor.png'),
(6029, 'Ironspike Whip', NULL, 'ironspike-whip.png'),
(6032, 'Stat Bonus', NULL, 'stat-bonus.png'),
(6035, 'Silvermere Dawn', NULL, 'silvermere-dawn.png'),
(6333, 'Death''s Dance', NULL, 'deaths-dance.png'),
(6609, 'Chempunk Chainsword', NULL, 'chempunk-chainsword.png'),
(6610, 'Sundered Sky', NULL, 'sundered-sky.png'),
(6616, 'Staff of Flowing Water', NULL, 'staff-of-flowing-water.png'),
(6617, 'Moonstone Renewer', NULL, 'moonstone-renewer.png'),
(6620, 'Echoes of Helia', NULL, 'echoes-of-helia.png'),
(6621, 'Dawncore', NULL, 'dawncore.png'),
(6630, 'Goredrinker', NULL, 'goredrinker.png'),
(663039, 'Atma''s Reckoning', NULL, 'atmas-reckoning.png'),
(663056, 'Demon King''s Crown', NULL, 'demon-kings-crown.png'),
(663058, 'Shield of Molten Stone', NULL, 'shield-of-molten-stone.png'),
(663059, 'Cloak of Starry Night', NULL, 'cloak-of-starry-night.png'),
(663060, 'Sword of the Divine', NULL, 'sword-of-the-divine.png'),
(663064, 'Veigar''s Talisman of Ascension', NULL, 'veigars-talisman-of-ascension.png'),
(6631, 'Stridebreaker', NULL, 'stridebreaker.png'),
(663146, 'Hextech Gunblade', NULL, 'hextech-gunblade.png'),
(663172, 'Zephyr', NULL, 'zephyr.png'),
(663193, 'Gargoyle Stoneplate', NULL, 'gargoyle-stoneplate.png'),
(6632, 'Divine Sunderer', NULL, 'divine-sunderer.png'),
(664011, 'Sword of Blossoming Dawn', NULL, 'sword-of-blossoming-dawn.png'),
(664403, 'The Golden Spatula', NULL, 'the-golden-spatula.png'),
(664644, 'Crown of the Shattered Queen', NULL, 'crown-of-the-shattered-queen.png'),
(6653, 'Liandry''s Torment', NULL, 'liandrys-torment.png'),
(6655, 'Luden''s Echo', NULL, 'ludens-echo.png'),
(6656, 'Everfrost', NULL, 'everfrost.png'),
(6657, 'Rod of Ages', NULL, 'rod-of-ages.png'),
(6660, 'Bami''s Cinder', NULL, 'bamis-cinder.png'),
(6662, 'Iceborn Gauntlet', NULL, 'iceborn-gauntlet.png'),
(6664, 'Hollow Radiance', NULL, 'hollow-radiance.png'),
(6665, 'Jak''Sho, The Protean', NULL, 'jaksho-the-protean.png'),
(6667, 'Radiant Virtue', NULL, 'radiant-virtue.png'),
(6670, 'Noonquiver', NULL, 'noonquiver.png'),
(6671, 'Galeforce', NULL, 'galeforce.png'),
(667101, 'Gambler''s Blade', NULL, 'gamblers-blade.png'),
(667109, 'Cruelty', NULL, 'cruelty.png'),
(667112, 'Flesheater', NULL, 'flesheater.png'),
(6672, 'Kraken Slayer', NULL, 'kraken-slayer.png'),
(6673, 'Immortal Shieldbow', NULL, 'immortal-shieldbow.png'),
(6675, 'Navori Flickerblade', NULL, 'navori-flickerblade.png'),
(6676, 'The Collector', NULL, 'the-collector.png'),
(667666, 'The Collector', NULL, 'the-collector.png'),
(6677, 'Rageknife', NULL, 'rageknife.png'),
(6690, 'Rectrix', NULL, 'rectrix.png'),
(6691, 'Duskblade of Draktharr', NULL, 'duskblade-of-draktharr.png'),
(6692, 'Eclipse', NULL, 'eclipse.png'),
(6693, 'Prowler''s Claw', NULL, 'prowlers-claw.png'),
(6694, 'Serylda''s Grudge', NULL, 'seryldas-grudge.png'),
(6695, 'Serpent''s Fang', NULL, 'serpents-fang.png'),
(6696, 'Axiom Arc', NULL, 'axiom-arc.png'),
(6697, 'Hubris', NULL, 'hubris.png'),
(6698, 'Profane Hydra', NULL, 'profane-hydra.png'),
(6699, 'Voltaic Cyclosword', NULL, 'voltaic-cyclosword.png'),
(6700, 'Shield of the Rakkor', NULL, 'shield-of-the-rakkor.png'),
(6701, 'Opportunity', NULL, 'opportunity.png'),
(6702, 'Scouting Ahead', NULL, 'scouting-ahead.png'),
(7050, 'Gangplank Placeholder', NULL, 'gangplank-placeholder.png'),
(8001, 'Anathema''s Chains', NULL, 'anathemas-chains.png'),
(8010, 'Bloodletter''s Curse', NULL, 'bloodletters-curse.png'),
(8020, 'Abyssal Mask', NULL, 'abyssal-mask.png'),
(9168, 'Locked Weapon Slot', NULL, 'locked-weapon-slot.png'),
(9171, 'Cyclonic Slicers', NULL, 'cyclonic-slicers.png'),
(9172, 'YuumiBot', NULL, 'yuumibot.png'),
(9173, 'Radiant Field', NULL, 'radiant-field.png'),
(9174, 'Statikk Sword', NULL, 'statikk-sword.png'),
(9175, 'Lioness''s Lament', NULL, 'lionesss-lament.png'),
(9176, 'Gatling Bunny-Guns', NULL, 'gatling-bunnyguns.png'),
(9177, 'Searing Shortbow', NULL, 'searing-shortbow.png'),
(9178, 'The Annihilator', NULL, 'the-annihilator.png'),
(9179, 'Battle Bunny Crossbow', NULL, 'battle-bunny-crossbow.png'),
(9180, 'UwU Blaster', NULL, 'uwu-blaster.png'),
(9181, 'Vortex Glove', NULL, 'vortex-glove.png'),
(9183, 'Blade-o-rang', NULL, 'bladeorang.png'),
(9184, 'Bunny Mega-Blast', NULL, 'bunny-megablast.png'),
(9185, 'Anti-Shark Sea Mine', NULL, 'antishark-sea-mine.png'),
(9187, 'T.I.B.B.E.R.S', NULL, 'tibbers.png'),
(9188, 'Ani-Mines', NULL, 'animines.png'),
(9189, 'Final City Transit', NULL, 'final-city-transit.png'),
(9190, 'Echoing Batblades', NULL, 'echoing-batblades.png'),
(9192, 'Paw Print Poisoner', NULL, 'paw-print-poisoner.png'),
(9193, 'Iceblast Armor', NULL, 'iceblast-armor.png'),
(9271, 'Unceasing Cyclone', NULL, 'unceasing-cyclone.png'),
(9272, 'YuumiBot_Final_FINAL', NULL, 'yuumibotfinalfinal.png'),
(9273, 'Explosive Embrace', NULL, 'explosive-embrace.png'),
(9274, 'Prumbis''s Electrocarver', NULL, 'prumbiss-electrocarver.png'),
(9275, 'Enveloping Light', NULL, 'enveloping-light.png'),
(9276, 'Double Bun-Bun Barrage', NULL, 'double-bunbun-barrage.png'),
(9277, 'Evolved Embershot', NULL, 'evolved-embershot.png'),
(9278, 'Animapocalypse', NULL, 'animapocalypse.png'),
(9279, 'Bunny Prime Ballista', NULL, 'bunny-prime-ballista.png'),
(9280, 'OwO Blaster', NULL, 'owo-blaster.png'),
(9281, 'Tempest''s Gauntlet', NULL, 'tempests-gauntlet.png'),
(9283, 'Quad-o-rang', NULL, 'quadorang.png'),
(9284, 'Rapid Rabbit Raindown', NULL, 'rapid-rabbit-raindown.png'),
(9285, 'Neverending Mobstomper', NULL, 'neverending-mobstomper.png'),
(9287, 'T.I.B.B.E.R.S (B.E.E.G Edition)', NULL, 'tibbers-beeg-edition.png'),
(9288, 'Jinx''s Tri-Namite', NULL, 'jinxs-trinamite.png'),
(9289, 'FC Limited Express', NULL, 'fc-limited-express.png'),
(9290, 'Vayne''s Chromablades', NULL, 'vaynes-chromablades.png'),
(9292, 'Bearfoot Chem-Dispenser', NULL, 'bearfoot-chemdispenser.png'),
(9293, 'Deep Freeze', NULL, 'deep-freeze.png'),
(9300, 'Meow Meow', NULL, 'meow-meow.png'),
(9301, 'Shield Slam', NULL, 'shield-slam.png'),
(9302, 'Sound Wave', NULL, 'sound-wave.png'),
(9303, 'Pillory Swipe', NULL, 'pillory-swipe.png'),
(9304, 'Steel Tempest', NULL, 'steel-tempest.png'),
(9305, 'Tentacle Slam', NULL, 'tentacle-slam.png'),
(9306, 'Winged Dagger', NULL, 'winged-dagger.png'),
(9307, 'Guiding Hex', NULL, 'guiding-hex.png'),
(9308, 'Bunny Hop', NULL, 'bunny-hop.png'),
(9400, 'Battle Cat Barrage', NULL, 'battle-cat-barrage.png'),
(9401, 'Light of the Lion', NULL, 'light-of-the-lion.png'),
(9402, 'Anima Echo', NULL, 'anima-echo.png'),
(9403, 'Savage Slice', NULL, 'savage-slice.png'),
(9404, 'Wandering Storms', NULL, 'wandering-storms.png'),
(9405, 'Grizzly Smash', NULL, 'grizzly-smash.png'),
(9406, 'Lover''s Ricochet', NULL, 'lovers-ricochet.png'),
(9407, 'Hopped-Up Hex', NULL, 'hoppedup-hex.png'),
(9408, 'Carrot Crash', NULL, 'carrot-crash.png'),
(994403, 'Golden Spatula', NULL, 'golden-spatula.png');
