-- Seed augments from frontend/augments.json (description omitted for performance)
INSERT INTO augments (id, name, description, tier, image) VALUES
(1, 'Accelerating Sorcery', NULL, 'Prismatic', 'acceleratingsorcery_large.png'),
(2, 'ADAPt', NULL, 'Silver', 'adapt_large.png'),
(3, 'All For You', NULL, 'Gold', 'allforyou_large.png'),
(4, 'Apex Inventor', NULL, 'Gold', 'apexinventor_large.png'),
(5, 'Back to Basics', NULL, 'Prismatic', 'backtobasics_large.png'),
(6, 'Banner of Command', NULL, 'Gold', 'bannerofcommand_large.png'),
(7, 'Big Brain', NULL, 'Gold', 'bigbrain_large.png'),
(8, 'Blade Waltz', NULL, 'Prismatic', 'bladewaltz_large.png'),
(9, 'Blood Brother', NULL, 'Gold', 'bloodbrother_large.png'),
(10, 'Blunt Force', NULL, 'Silver', 'bluntforce_large.png'),
(11, 'Bread And Butter', NULL, 'Gold', 'breadandbutter_large.png'),
(12, 'Bread And Cheese', NULL, 'Gold', 'breadandcheese_large.png'),
(13, 'Bread And Jam', NULL, 'Gold', 'breadandjam_large.png'),
(14, 'Buff Buddies', NULL, 'Silver', 'buffbuddies_large.png'),
(15, 'Can''t Touch This', NULL, 'Prismatic', 'canttouchthis_large.png'),
(16, 'Cannon Fodder', NULL, 'Gold', 'cannonfodder_large.png'),
(17, 'Castle', NULL, 'Silver', 'castle_large.png'),
(18, 'Celestial Body', NULL, 'Gold', 'celestialbody_large.png'),
(19, 'Center of the Universe', NULL, 'Prismatic', 'centeroftheuniverse_large.png'),
(20, 'Chain Lightning', NULL, 'Prismatic', 'chainlightning_large.png'),
(21, 'Chauffeur', NULL, 'Prismatic', 'chauffeur_large.png'),
(22, 'Circle of Death', NULL, 'Prismatic', 'circleofdeath_large.png'),
(23, 'Clothesline', NULL, 'Silver', 'clothesline_large.png'),
(24, 'Combo Master', NULL, 'Gold', 'combomaster_large.png'),
(25, 'Contract Killer', NULL, 'Silver', 'contractkiller_large.png'),
(26, 'Courage of the Colossus', NULL, 'Prismatic', 'courageofthecolossus_large.png'),
(27, 'Critical Healing', NULL, 'Gold', 'criticalhealing_large.png'),
(28, 'Dashing', NULL, 'Prismatic', 'dashing_large.png'),
(29, 'Dawnbringer''s Resolve', NULL, 'Gold', 'dawnbringersresolve_large.png'),
(30, 'Defensive Maneuvers', NULL, 'Gold', 'defensivemaneuvers_large.png'),
(31, 'Deft', NULL, 'Silver', 'deft_large.png'),
(32, 'Dematerialize', NULL, 'Silver', 'dematerialize_large.png'),
(33, 'Demon''s Dance', NULL, 'Gold', 'demonsdance_large.png'),
(34, 'Die Another Day', NULL, 'Gold', 'dieanotherday_large.png'),
(35, 'Dive Bomber', NULL, 'Gold', 'divebomber_large.png'),
(36, 'Don''t Blink', NULL, 'Silver', 'dontblink_large.png'),
(37, 'Don''t Chase', NULL, 'Silver', 'dontchase_large.png'),
(38, 'Draw Your Sword', NULL, 'Prismatic', 'drawyoursword_large.png'),
(39, 'Dual Wield', NULL, 'Prismatic', 'dualwield_large.png'),
(40, 'Earthwake', NULL, 'Prismatic', 'earthwake_large.png'),
(41, 'Erosion', NULL, 'Silver', 'erosion_large.png'),
(42, 'EscAPADe', NULL, 'Silver', 'escapade_large.png'),
(43, 'Ethereal Weapon', NULL, 'Gold', 'etherealweapon_large.png'),
(44, 'Eureka', NULL, 'Prismatic', 'eureka_large.png'),
(45, 'Executioner', NULL, 'Silver', 'executioner_large.png'),
(46, 'Extendo-Arm', NULL, 'Gold', 'extendoarm_large.png'),
(47, 'Fallen Aegis', NULL, 'Silver', 'fallenaegis_large.png'),
(48, 'Fan the Hammer', NULL, 'Prismatic', 'fanthehammer_large.png'),
(49, 'Feel the Burn', NULL, 'Prismatic', 'feeltheburn_large.png'),
(50, 'Fey Magic', NULL, 'Prismatic', 'feymagic_large.png'),
(51, 'Fire Sale', NULL, 'Silver', 'firesale_large.png'),
(52, 'Firebrand', NULL, 'Gold', 'firebrand_large.png'),
(53, 'First-Aid Kit', NULL, 'Silver', 'firstaidkit_large.png'),
(54, 'Flashbang', NULL, 'Silver', 'flashbang_large.png'),
(55, 'Flashy', NULL, 'Silver', 'flashy_large.png'),
(56, 'From Beginning to End', NULL, 'Gold', 'frombeginningtoend_large.png'),
(57, 'Frost Wraith', NULL, 'Silver', 'frostwraith_large.png'),
(58, 'Frozen Foundations', NULL, 'Silver', 'frozenfoundations_large.png'),
(59, 'Fruits of Your Labor', NULL, 'Gold', 'fruitarian_large.png'),
(60, 'Gamba Anvil', NULL, 'Prismatic', 'thiefsgloves_large.png'),
(61, 'Giant Slayer', NULL, 'Prismatic', 'giantslayer_large.png'),
(62, 'Goliath', NULL, 'Prismatic', 'goliath_large.png'),
(63, 'Goredrink', NULL, 'Silver', 'goredrink_large.png'),
(64, 'Guilty Pleasure', NULL, 'Silver', 'guiltypleasure_large.png'),
(65, 'Heavy Hitter', NULL, 'Silver', 'heavyhitter_large.png'),
(66, 'Hold Very Still', NULL, 'Silver', 'holdverystill_large.png'),
(67, 'Holy Fire', NULL, 'Gold', 'holyfire_large.png'),
(68, 'Homeguard', NULL, 'Silver', 'homeguard_large.png'),
(69, 'Ice Cold', NULL, 'Silver', 'icecold_large.png'),
(70, 'Impassable', NULL, 'Gold', 'impassable_large.png'),
(71, 'Infernal Conduit', NULL, 'Prismatic', 'infernalconduit_large.png'),
(72, 'Infernal Soul', NULL, 'Silver', 'infernalsoul_large.png'),
(73, 'It''s Critical', NULL, 'Gold', 'itscritical_large.png'),
(74, 'It''s Killing Time', NULL, 'Gold', 'itskillingtime_large.png'),
(75, 'Jeweled Gauntlet', NULL, 'Prismatic', 'jeweledgauntlet_large.png'),
(76, 'Juice Box', NULL, 'Silver', 'juicebox_large.png'),
(77, 'Keystone Conjurer', NULL, 'Gold', 'keystoneconjurer_large.png'),
(78, 'Laser Eyes', NULL, 'Prismatic', 'lasereyes_large.png'),
(79, 'Light ''em Up!', NULL, 'Silver', 'lightemup_large.png'),
(80, 'Light Warden', NULL, 'Gold', 'lightwarden_large.png'),
(81, 'Lightning Strikes', NULL, 'Gold', 'lightningstrikes_large.png'),
(82, 'Mad Scientist', NULL, 'Prismatic', 'madscientist_large.png'),
(83, 'Magic Missile', NULL, 'Gold', 'magicmissile_large.png'),
(84, 'Marksmage', NULL, 'Gold', 'marksmage_large.png'),
(85, 'Master of Duality', NULL, 'Prismatic', 'masterofduality_large.png'),
(86, 'Mind to Matter', NULL, 'Silver', 'mindtomatter_large.png'),
(87, 'Minionmancer', NULL, 'Gold', 'minionmancer_large.png'),
(88, 'Mirror Image', NULL, 'Silver', 'mirrorimage_large.png'),
(89, 'Mountain Soul', NULL, 'Silver', 'mountainsoul_large.png'),
(90, 'Mystic Punch', NULL, 'Prismatic', 'mysticpunch_large.png'),
(91, 'Nesting Doll', NULL, 'Prismatic', 'nestingdoll_large.png'),
(92, 'Now You See Me', NULL, 'Silver', 'nowyouseeme_large.png'),
(93, 'Oathsworn', NULL, 'Gold', 'oathsworn_large.png'),
(94, 'Ocean Soul', NULL, 'Silver', 'oceansoul_large.png'),
(95, 'OK Boomerang', NULL, 'Gold', 'okboomerang_large.png'),
(96, 'Omni Soul', NULL, 'Prismatic', 'omnisoul_large.png'),
(97, 'Orbital Laser', NULL, 'Prismatic', 'orbitallaser_large.png'),
(98, 'Outlaw''s Grit', NULL, 'Gold', 'outlawsgrit_large.png'),
(99, 'Parasitic Relationship', NULL, 'Gold', 'parasiticrelationship_large.png'),
(100, 'Perseverance', NULL, 'Gold', 'perseverance_large.png'),
(101, 'Phenomenal Evil', NULL, 'Gold', 'phenomenalevil_large.png'),
(102, 'Prismatic Egg', NULL, 'Prismatic', 'quest_prismaticegg_large.png'),
(103, 'Quantum Computing', NULL, 'Prismatic', 'quantumcomputing_large.png'),
(104, 'Quest: Angel of Retribution', NULL, 'Gold', 'quest_angelofretribution_large.png'),
(105, 'Quest: Steel Your Heart', NULL, 'Gold', 'quest_steelyourheart_large.png'),
(106, 'Quest: Urf''s Champion', NULL, 'Gold', 'quest_urfschampion_large.png'),
(107, 'Quest: Wooglet''s Witchcap', NULL, 'Prismatic', 'quest_woogletswitchcap_large.png'),
(108, 'Rabble Rousing', NULL, 'Gold', 'rabblerousing_large.png'),
(137, 'Summoner''s Roulette', NULL, 'Prismatic', 'summonersroulette_large.png'),
(109, 'Raid Boss', NULL, 'Prismatic', 'raidboss_large.png'),
(110, 'Recursion', NULL, 'Gold', 'recursion_large.png'),
(111, 'Repulsor', NULL, 'Silver', 'repulsor_large.png'),
(112, 'Restart', NULL, 'Gold', 'restart_large.png'),
(113, 'Restless Restoration', NULL, 'Gold', 'restlessrestoration_large.png'),
(114, 'Scoped Weapons', NULL, 'Silver', 'scopedweapons_large.png'),
(115, 'Scopier Weapons', NULL, 'Gold', 'scopierweapons_large.png'),
(116, 'Scopiest Weapons', NULL, 'Prismatic', 'scopiestweapons_large.png'),
(117, 'Searing Dawn', NULL, 'Gold', 'searingdawn_large.png'),
(118, 'Self Destruct', NULL, 'Silver', 'selfdestruct_large.png'),
(119, 'Serve Beyond Death', NULL, 'Silver', 'servebeyonddeath_large.png'),
(120, 'Shadow Runner', NULL, 'Silver', 'shadowrunner_large.png'),
(121, 'Shrink Ray', NULL, 'Gold', 'shrinkray_large.png'),
(122, 'Skilled Sniper', NULL, 'Gold', 'skilledsniper_large.png'),
(123, 'Slap Around', NULL, 'Silver', 'slaparound_large.png'),
(124, 'Slime Time', NULL, 'Silver', 'slimetime_large.png'),
(125, 'Slow Cooker', NULL, 'Prismatic', 'slowcooker_large.png'),
(126, 'Snowball Fight!', NULL, 'Silver', 'snowballfight_large.png'),
(127, 'Sonic Boom', NULL, 'Silver', 'sonicboom_large.png'),
(128, 'Soul Siphon', NULL, 'Gold', 'soulsiphon_large.png'),
(129, 'Spellwake', NULL, 'Prismatic', 'spellwake_large.png'),
(130, 'Spin To Win', NULL, 'Silver', 'spintowin_large.png'),
(131, 'Spirit Link', NULL, 'Prismatic', 'spiritlink_large.png'),
(132, 'Stackosaurus Rex', NULL, 'Silver', 'stackosaurusrex_large.png'),
(133, 'Stats!', NULL, 'Silver', 'stats_large.png'),
(134, 'Stats on Stats!', NULL, 'Gold', 'statsonstats_large.png'),
(135, 'Stats on Stats on Stats!', NULL, 'Prismatic', 'statsonstatsonstats_large.png'),
(136, 'Summoner Revolution', NULL, 'Gold', 'summonerrevolution_large.png'),
(138, 'Symphony of War', NULL, 'Prismatic', 'symphonyofwar_large.png'),
(139, 'Tank It Or Leave It', NULL, 'Silver', 'tankitorleaveit_large.png'),
(140, 'Tap Dancer', NULL, 'Prismatic', 'tapdancer_large.png'),
(141, 'The Brutalizer', NULL, 'Gold', 'thebrutalizer_large.png'),
(142, 'Thread the Needle', NULL, 'Gold', 'threadtheneedle_large.png'),
(143, 'Tormentor', NULL, 'Silver', 'tormentor_large.png'),
(144, 'Trailblazer', NULL, 'Silver', 'trailblazer_large.png'),
(145, 'Trueshot Prodigy', NULL, 'Prismatic', 'trueshotprodigy_large.png'),
(146, 'Twice Thrice', NULL, 'Gold', 'twicethrice_large.png'),
(147, 'Typhoon', NULL, 'Silver', 'typhoon_large.png'),
(148, 'Ultimate Revolution', NULL, 'Prismatic', 'ultimaterevolution_large.png'),
(149, 'Ultimate Roulette', NULL, 'Prismatic', 'ultimaterevolution_large.png'),
(150, 'Ultimate Unstoppable', NULL, 'Silver', 'ultimateunstoppable_large.png'),
(151, 'Vanish', NULL, 'Gold', 'vanish_large.png'),
(152, 'Vengeance', NULL, 'Gold', 'vengeance_large.png'),
(153, 'Vulnerability', NULL, 'Silver', 'vulnerability_large.png'),
(154, 'Warmup Routine', NULL, 'Silver', 'warmuproutine_large.png'),
(155, 'Willing Sacrifice', NULL, 'Gold', 'willingsacrifice_large.png'),
(156, 'Wisdom of Ages', NULL, 'Prismatic', 'wisdomofages_large.png'),
(157, 'Witchful Thinking', NULL, 'Silver', 'witchfulthinking_large.png'),
(158, 'With Haste', NULL, 'Gold', 'withhaste_large.png');
