-- Add tags column to champions
ALTER TABLE champions ADD COLUMN tags varchar[];

-- Seed champion tags from frontend/champs.json
UPDATE champions SET tags = ARRAY['Fighter'] WHERE id = 'Aatrox';
UPDATE champions SET tags = ARRAY['Mage', 'Assassin'] WHERE id = 'Ahri';
UPDATE champions SET tags = ARRAY['Assassin'] WHERE id = 'Akali';
UPDATE champions SET tags = ARRAY['Marksman', 'Assassin'] WHERE id = 'Akshan';
UPDATE champions SET tags = ARRAY['Tank', 'Support'] WHERE id = 'Alistar';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Ambessa';
UPDATE champions SET tags = ARRAY['Tank', 'Support'] WHERE id = 'Amumu';
UPDATE champions SET tags = ARRAY['Mage'] WHERE id = 'Anivia';
UPDATE champions SET tags = ARRAY['Mage', 'Support'] WHERE id = 'Annie';
UPDATE champions SET tags = ARRAY['Marksman'] WHERE id = 'Aphelios';
UPDATE champions SET tags = ARRAY['Marksman', 'Support'] WHERE id = 'Ashe';
UPDATE champions SET tags = ARRAY['Mage'] WHERE id = 'AurelionSol';
UPDATE champions SET tags = ARRAY['Mage', 'Assassin'] WHERE id = 'Aurora';
UPDATE champions SET tags = ARRAY['Mage', 'Marksman'] WHERE id = 'Azir';
UPDATE champions SET tags = ARRAY['Support', 'Mage'] WHERE id = 'Bard';
UPDATE champions SET tags = ARRAY['Fighter'] WHERE id = 'Belveth';
UPDATE champions SET tags = ARRAY['Tank', 'Support'] WHERE id = 'Blitzcrank';
UPDATE champions SET tags = ARRAY['Mage', 'Support'] WHERE id = 'Brand';
UPDATE champions SET tags = ARRAY['Tank', 'Support'] WHERE id = 'Braum';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Briar';
UPDATE champions SET tags = ARRAY['Marksman'] WHERE id = 'Caitlyn';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Camille';
UPDATE champions SET tags = ARRAY['Mage'] WHERE id = 'Cassiopeia';
UPDATE champions SET tags = ARRAY['Tank', 'Mage'] WHERE id = 'Chogath';
UPDATE champions SET tags = ARRAY['Marksman', 'Mage'] WHERE id = 'Corki';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'Darius';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Diana';
UPDATE champions SET tags = ARRAY['Marksman'] WHERE id = 'Draven';
UPDATE champions SET tags = ARRAY['Tank', 'Fighter'] WHERE id = 'DrMundo';
UPDATE champions SET tags = ARRAY['Assassin', 'Mage'] WHERE id = 'Ekko';
UPDATE champions SET tags = ARRAY['Assassin', 'Mage'] WHERE id = 'Elise';
UPDATE champions SET tags = ARRAY['Assassin', 'Mage'] WHERE id = 'Evelynn';
UPDATE champions SET tags = ARRAY['Marksman', 'Mage'] WHERE id = 'Ezreal';
UPDATE champions SET tags = ARRAY['Mage', 'Support'] WHERE id = 'Fiddlesticks';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Fiora';
UPDATE champions SET tags = ARRAY['Assassin', 'Fighter'] WHERE id = 'Fizz';
UPDATE champions SET tags = ARRAY['Tank', 'Mage'] WHERE id = 'Galio';
UPDATE champions SET tags = ARRAY['Fighter'] WHERE id = 'Gangplank';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'Garen';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'Gnar';
UPDATE champions SET tags = ARRAY['Fighter', 'Mage'] WHERE id = 'Gragas';
UPDATE champions SET tags = ARRAY['Marksman'] WHERE id = 'Graves';
UPDATE champions SET tags = ARRAY['Fighter'] WHERE id = 'Gwen';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'Hecarim';
UPDATE champions SET tags = ARRAY['Mage', 'Support'] WHERE id = 'Heimerdinger';
UPDATE champions SET tags = ARRAY['Mage', 'Support'] WHERE id = 'Hwei';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'Illaoi';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Irelia';
UPDATE champions SET tags = ARRAY['Support', 'Mage'] WHERE id = 'Ivern';
UPDATE champions SET tags = ARRAY['Support', 'Mage'] WHERE id = 'Janna';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'JarvanIV';
UPDATE champions SET tags = ARRAY['Fighter'] WHERE id = 'Jax';
UPDATE champions SET tags = ARRAY['Fighter', 'Marksman'] WHERE id = 'Jayce';
UPDATE champions SET tags = ARRAY['Marksman', 'Mage'] WHERE id = 'Jhin';
UPDATE champions SET tags = ARRAY['Marksman'] WHERE id = 'Jinx';
UPDATE champions SET tags = ARRAY['Marksman', 'Mage'] WHERE id = 'Kaisa';
UPDATE champions SET tags = ARRAY['Marksman'] WHERE id = 'Kalista';
UPDATE champions SET tags = ARRAY['Mage', 'Support'] WHERE id = 'Karma';
UPDATE champions SET tags = ARRAY['Mage'] WHERE id = 'Karthus';
UPDATE champions SET tags = ARRAY['Assassin', 'Mage'] WHERE id = 'Kassadin';
UPDATE champions SET tags = ARRAY['Assassin', 'Mage'] WHERE id = 'Katarina';
UPDATE champions SET tags = ARRAY['Mage', 'Marksman'] WHERE id = 'Kayle';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Kayn';
UPDATE champions SET tags = ARRAY['Mage'] WHERE id = 'Kennen';
UPDATE champions SET tags = ARRAY['Assassin'] WHERE id = 'Khazix';
UPDATE champions SET tags = ARRAY['Marksman'] WHERE id = 'Kindred';
UPDATE champions SET tags = ARRAY['Fighter'] WHERE id = 'Kled';
UPDATE champions SET tags = ARRAY['Marksman', 'Mage'] WHERE id = 'KogMaw';
UPDATE champions SET tags = ARRAY['Tank', 'Fighter'] WHERE id = 'KSante';
UPDATE champions SET tags = ARRAY['Assassin', 'Mage'] WHERE id = 'Leblanc';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'LeeSin';
UPDATE champions SET tags = ARRAY['Tank', 'Support'] WHERE id = 'Leona';
UPDATE champions SET tags = ARRAY['Fighter', 'Mage'] WHERE id = 'Lillia';
UPDATE champions SET tags = ARRAY['Mage'] WHERE id = 'Lissandra';
UPDATE champions SET tags = ARRAY['Marksman', 'Assassin'] WHERE id = 'Lucian';
UPDATE champions SET tags = ARRAY['Support', 'Mage'] WHERE id = 'Lulu';
UPDATE champions SET tags = ARRAY['Mage', 'Support'] WHERE id = 'Lux';
UPDATE champions SET tags = ARRAY['Tank', 'Mage'] WHERE id = 'Malphite';
UPDATE champions SET tags = ARRAY['Mage'] WHERE id = 'Malzahar';
UPDATE champions SET tags = ARRAY['Tank', 'Support'] WHERE id = 'Maokai';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'MasterYi';
UPDATE champions SET tags = ARRAY['Mage', 'Support'] WHERE id = 'Mel';
UPDATE champions SET tags = ARRAY['Support', 'Mage'] WHERE id = 'Milio';
UPDATE champions SET tags = ARRAY['Marksman', 'Mage'] WHERE id = 'MissFortune';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'MonkeyKing';
UPDATE champions SET tags = ARRAY['Fighter', 'Mage'] WHERE id = 'Mordekaiser';
UPDATE champions SET tags = ARRAY['Support', 'Mage'] WHERE id = 'Morgana';
UPDATE champions SET tags = ARRAY['Assassin', 'Fighter'] WHERE id = 'Naafiri';
UPDATE champions SET tags = ARRAY['Support', 'Mage'] WHERE id = 'Nami';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'Nasus';
UPDATE champions SET tags = ARRAY['Tank', 'Support'] WHERE id = 'Nautilus';
UPDATE champions SET tags = ARRAY['Mage', 'Support'] WHERE id = 'Neeko';
UPDATE champions SET tags = ARRAY['Assassin', 'Mage'] WHERE id = 'Nidalee';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Nilah';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Nocturne';
UPDATE champions SET tags = ARRAY['Tank', 'Mage'] WHERE id = 'Nunu';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'Olaf';
UPDATE champions SET tags = ARRAY['Mage', 'Support'] WHERE id = 'Orianna';
UPDATE champions SET tags = ARRAY['Tank'] WHERE id = 'Ornn';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Pantheon';
UPDATE champions SET tags = ARRAY['Tank', 'Fighter'] WHERE id = 'Poppy';
UPDATE champions SET tags = ARRAY['Support', 'Assassin'] WHERE id = 'Pyke';
UPDATE champions SET tags = ARRAY['Assassin'] WHERE id = 'Qiyana';
UPDATE champions SET tags = ARRAY['Marksman', 'Assassin'] WHERE id = 'Quinn';
UPDATE champions SET tags = ARRAY['Support'] WHERE id = 'Rakan';
UPDATE champions SET tags = ARRAY['Tank'] WHERE id = 'Rammus';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'RekSai';
UPDATE champions SET tags = ARRAY['Tank', 'Support'] WHERE id = 'Rell';
UPDATE champions SET tags = ARRAY['Support', 'Mage'] WHERE id = 'Renata';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'Renekton';
UPDATE champions SET tags = ARRAY['Assassin', 'Fighter'] WHERE id = 'Rengar';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Riven';
UPDATE champions SET tags = ARRAY['Fighter', 'Mage'] WHERE id = 'Rumble';
UPDATE champions SET tags = ARRAY['Mage'] WHERE id = 'Ryze';
UPDATE champions SET tags = ARRAY['Marksman', 'Assassin'] WHERE id = 'Samira';
UPDATE champions SET tags = ARRAY['Tank'] WHERE id = 'Sejuani';
UPDATE champions SET tags = ARRAY['Support', 'Marksman'] WHERE id = 'Senna';
UPDATE champions SET tags = ARRAY['Support', 'Mage'] WHERE id = 'Seraphine';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'Sett';
UPDATE champions SET tags = ARRAY['Assassin'] WHERE id = 'Shaco';
UPDATE champions SET tags = ARRAY['Tank'] WHERE id = 'Shen';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'Shyvana';
UPDATE champions SET tags = ARRAY['Tank', 'Mage'] WHERE id = 'Singed';
UPDATE champions SET tags = ARRAY['Tank', 'Fighter'] WHERE id = 'Sion';
UPDATE champions SET tags = ARRAY['Marksman'] WHERE id = 'Sivir';
UPDATE champions SET tags = ARRAY['Tank', 'Fighter'] WHERE id = 'Skarner';
UPDATE champions SET tags = ARRAY['Marksman', 'Mage'] WHERE id = 'Smolder';
UPDATE champions SET tags = ARRAY['Support', 'Mage'] WHERE id = 'Sona';
UPDATE champions SET tags = ARRAY['Support', 'Mage'] WHERE id = 'Soraka';
UPDATE champions SET tags = ARRAY['Mage', 'Support'] WHERE id = 'Swain';
UPDATE champions SET tags = ARRAY['Mage', 'Assassin'] WHERE id = 'Sylas';
UPDATE champions SET tags = ARRAY['Mage'] WHERE id = 'Syndra';
UPDATE champions SET tags = ARRAY['Tank', 'Support'] WHERE id = 'TahmKench';
UPDATE champions SET tags = ARRAY['Mage', 'Support'] WHERE id = 'Taliyah';
UPDATE champions SET tags = ARRAY['Assassin'] WHERE id = 'Talon';
UPDATE champions SET tags = ARRAY['Support', 'Tank'] WHERE id = 'Taric';
UPDATE champions SET tags = ARRAY['Marksman', 'Mage'] WHERE id = 'Teemo';
UPDATE champions SET tags = ARRAY['Support', 'Tank'] WHERE id = 'Thresh';
UPDATE champions SET tags = ARRAY['Marksman', 'Assassin'] WHERE id = 'Tristana';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'Trundle';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Tryndamere';
UPDATE champions SET tags = ARRAY['Mage', 'Marksman'] WHERE id = 'TwistedFate';
UPDATE champions SET tags = ARRAY['Marksman', 'Assassin'] WHERE id = 'Twitch';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'Udyr';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'Urgot';
UPDATE champions SET tags = ARRAY['Marksman', 'Mage'] WHERE id = 'Varus';
UPDATE champions SET tags = ARRAY['Marksman', 'Assassin'] WHERE id = 'Vayne';
UPDATE champions SET tags = ARRAY['Mage'] WHERE id = 'Veigar';
UPDATE champions SET tags = ARRAY['Mage', 'Support'] WHERE id = 'Velkoz';
UPDATE champions SET tags = ARRAY['Mage'] WHERE id = 'Vex';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Vi';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Viego';
UPDATE champions SET tags = ARRAY['Mage'] WHERE id = 'Viktor';
UPDATE champions SET tags = ARRAY['Mage', 'Fighter'] WHERE id = 'Vladimir';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'Volibear';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'Warwick';
UPDATE champions SET tags = ARRAY['Marksman'] WHERE id = 'Xayah';
UPDATE champions SET tags = ARRAY['Mage', 'Support'] WHERE id = 'Xerath';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'XinZhao';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Yasuo';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Yone';
UPDATE champions SET tags = ARRAY['Fighter', 'Tank'] WHERE id = 'Yorick';
UPDATE champions SET tags = ARRAY['Marksman'] WHERE id = 'Yunara';
UPDATE champions SET tags = ARRAY['Support', 'Mage'] WHERE id = 'Yuumi';
UPDATE champions SET tags = ARRAY['Fighter', 'Assassin'] WHERE id = 'Zaahen';
UPDATE champions SET tags = ARRAY['Tank', 'Fighter'] WHERE id = 'Zac';
UPDATE champions SET tags = ARRAY['Assassin'] WHERE id = 'Zed';
UPDATE champions SET tags = ARRAY['Marksman'] WHERE id = 'Zeri';
UPDATE champions SET tags = ARRAY['Mage'] WHERE id = 'Ziggs';
UPDATE champions SET tags = ARRAY['Support', 'Mage'] WHERE id = 'Zilean';
UPDATE champions SET tags = ARRAY['Mage'] WHERE id = 'Zoe';
UPDATE champions SET tags = ARRAY['Mage', 'Support'] WHERE id = 'Zyra';